export const stateDistrictCityData = {
  "Andaman and Nicobar Islands": {
    "Nicobars": [
      "Car Nicobar",
      "Great Nicobar",
      "Nancowry"
    ],
    "North and Middle Andaman": [
      "Diglipur",
      "Mayabunder",
      "Rangat"
    ],
    "South Andamans": [
      "Ferrargunj",
      "Little Andaman",
      "Port Blair"
    ]
  },

  "Andhra Pradesh": {
    "Alluri Sitharama Raju": [
      "Addateegala",
      "Ananthagiri",
      "Araku Valley",
      "Chinthapalli",
      "Chinturu",
      "Devipatnam",
      "Dumbriguda",
      "G.Madugula",
      "Gangavaram",
      "Gudem Kotha Veedhi",
      "Hukumpeta",
      "Koyyuru",
      "Kunavaram",
      "Maredumilli",
      "Munchingi Puttu",
      "Paderu",
      "Peda Bayalu",
      "Rajavommangi",
      "Rampachodavaram",
      "Vararamachandrapuram",
      "Y. Ramavaram",
      "Yetapaka"
    ],
    "Anakapalli": [
      "Anakapalli",
      "Atchuthapuram",
      "Butchayyapeta",
      "Cheedikada",
      "Chodavaram",
      "Devarapalli",
      "Golugonda",
      "K.Kotapadu",
      "Kasimkota",
      "Kotauratla",
      "Madugula",
      "Makavarapalem",
      "Munagapaka",
      "Nakkapalli",
      "Narsipatnam",
      "Nathavaram",
      "Paravada",
      "Payakaraopeta",
      "Rambilli",
      "Ravikamatham",
      "Rolugunta",
      "S.Rayavaram",
      "Sabbavaram",
      "Yelamanchili"
    ],
    "Ananthapuramu": [
      "Anantapur Rural",
      "Anantapur Urban",
      "Atmakur",
      "Beluguppa",
      "Bommanahal",
      "Brahmasamudram",
      "Bukkaraya Samudram",
      "D.Hirehal",
      "Garladinne",
      "Gooty",
      "Gummagatta",
      "Guntakal",
      "Kalyanadurg",
      "Kambadur",
      "Kanekal",
      "Kudair",
      "Kundurpi",
      "Narpala",
      "Pamidi",
      "Peddapappur",
      "Peddavaduguru",
      "Putlur",
      "Rapthadu",
      "Rayadurg",
      "Settur",
      "Singanamala",
      "Tadipatri",
      "Uravakonda",
      "Vajrakarur",
      "Vidapanakal",
      "Yadiki",
      "Yellanur"
    ],
    "Annamayya": [
      "Beerongi Kothakota",
      "Chinnamandem",
      "Chitvel",
      "Galiveedu",
      "Gurramkonda",
      "Kalakada",
      "Kalikiri",
      "Kambhamvaripalle",
      "Kodur",
      "Kurabalakota",
      "Lakkireddipalli",
      "Madanapalle",
      "Mulakalacheruvu",
      "Nandalur",
      "Nimmanapalle",
      "Obulavaripalle",
      "Pedda Thippasamudram",
      "Peddamandyam",
      "Penagalur",
      "Pileru",
      "Pullampeta",
      "Rajampet",
      "Ramapuram",
      "Ramasamudram",
      "Rayachoti",
      "Sambepalle",
      "T.Sundupalle",
      "Thamballapalle",
      "Valmikipuram",
      "Veeraballe"
    ],
    "Bapatla": [
      "Addanki",
      "Amarthalur",
      "Ballikurava",
      "Bapatla",
      "Bhattiprolu",
      "Cherukupalli",
      "Chinaganjam",
      "Chirala",
      "Inkollu",
      "J.Pangulur",
      "Karamchedu",
      "Karlapalem",
      "Kolluru",
      "Korisapadu",
      "Martur",
      "Nagaram",
      "Nizampatnam",
      "Parchur",
      "Pittalavanipalem",
      "Repalle",
      "Santhamaguluru",
      "Tsunduru",
      "Vemuru",
      "Vetapalem",
      "Yeddana Pudi"
    ],
    "Chittoor": [
      "Baireddipalle",
      "Bangarupalem",
      "Chittoor Rural",
      "Chittoor Urban",
      "Chowdepalle",
      "Gangadhara Nellore",
      "Gangavaram",
      "Gudipala",
      "Gudupalle",
      "Irala",
      "Karvetinagar",
      "Kuppam",
      "Nagari",
      "Nindra",
      "Palamaner",
      "Palasamudram",
      "Peddapanjani",
      "Penumur",
      "Pulicherla",
      "Punganuru",
      "Puthalapattu",
      "Ramakuppam",
      "Rompicherla",
      "Santhipuram",
      "Sodam",
      "Vijayapuram",
      "Yadamarri",
      "Somala",
      "Srirangarajapuram",
      "Thavanampalle",
      "Vedurukuppam",
      "Venkatagirikota"
    ],
    "Dr. B.R. Ambedkar Konaseema": [
      "Ainavilli",
      "Alamuru",
      "Allavaram",
      "Amalapuram",
      "Ambajipeta",
      "Atreyapuram",
      "I. Polavaram",
      "K Gangavaram",
      "Kapileswarapuram",
      "Katrenikona",
      "Kothapeta",
      "Malikipuram",
      "Mamidikuduru",
      "Mandapeta",
      "Mummidivaram",
      "P.Gannavaram",
      "Ramachandrapuram",
      "Ravulapalem",
      "Rayavaram",
      "Razole",
      "Sakhinetipalli",
      "Uppalaguptam"
    ],
    "East Godavari": [
      "Anaparthi",
      "Biccavolu",
      "Chagallu",
      "Devarapalle",
      "Gokavaram",
      "Gopalapuram",
      "Kadiam",
      "Korukonda",
      "Kovvur",
      "Nallajerla",
      "Nidadavole",
      "Peravali",
      "Rajamahendravaram Rural",
      "Rajamahendravaram Urban",
      "Rajanagaram",
      "Rangampeta",
      "Seethanagaram",
      "Tallapudi",
      "Undrajavaram"
    ],
    "Eluru": [
      "Agiripalli",
      "Bheemadole",
      "Buttayagudem",
      "Chatrai",
      "Chintalapudi",
      "Denduluru",
      "Dwarakatirumala",
      "Eluru Rural",
      "Eluru Urban",
      "Jangareddigudem",
      "Jeelugu Milli",
      "Kaikaluru",
      "Kalidindi",
      "Kamavarapukota",
      "Koyyalagudem",
      "Kukunoor",
      "Lingapalem",
      "Mandavalli",
      "Mudinepalle",
      "Musunuru",
      "Nidamarru",
      "Nuzividu",
      "Pedapadu",
      "Pedavegi",
      "Polavaram",
      "T.Narasapuram",
      "Unguturu",
      "Velairpadu"
    ],
    "Guntur": [
      "Chebrolu",
      "Duggirala",
      "Guntur East",
      "Guntur West",
      "Kakumanu",
      "Kollipara",
      "Mangalagiri",
      "Medikonduru",
      "Pedakakani",
      "Pedanandipadu",
      "Phirangipuram",
      "Ponnur",
      "Prathipadu",
      "Tadepalli",
      "Tadikonda",
      "Tenali",
      "Thulluru",
      "Vatticherukuru"
    ],
    "Kakinada": [
      "Gandepalli",
      "Gollaprolu",
      "Jaggampeta",
      "Kajuluru",
      "Kakinada (Rural)",
      "Kakinada (Urban)",
      "Karapa",
      "Kirlampudi",
      "Kotananduru",
      "Pedapudi",
      "Peddapuram",
      "Pithapuram",
      "Prathipadu",
      "Rowthulapudi",
      "Samalkota",
      "Sankhavaram",
      "Tallarevu",
      "Thondangi",
      "Tuni",
      "U.Kothapalli",
      "Yeleswaram"
    ],
    "Krishna": [
      "Avanigadda",
      "Bantumilli",
      "Bapulapadu",
      "Challapalli",
      "Gannavaram",
      "Ghantasala",
      "Gudivada",
      "Gudlavalleru",
      "Guduru",
      "Kankipadu",
      "Koduru",
      "Kruthivennu",
      "Machilipatnam North",
      "Machilipatnam South",
      "Mopidevi",
      "Movva",
      "Nagayalanka",
      "Nandivada",
      "Pamarru",
      "Pamidimukkala",
      "Pedana",
      "Pedaparupudi",
      "Penamaluru",
      "Thotlavalluru",
      "Unguturu",
      "Vuyyuru"
    ],
    "Kurnool": [
      "Adoni",
      "Alur",
      "Aspari",
      "C.Belagal",
      "Chippagiri",
      "Devanakonda",
      "Gonegandla",
      "Gudur",
      "Halaharvi",
      "Holagunda",
      "Kallur",
      "Kodumur",
      "Kosigi",
      "Kowthalam",
      "Krishnagiri",
      "Kurnool Rural",
      "Kurnool Urban",
      "Maddikera (East)",
      "Mantralayam",
      "Nandavaram",
      "Orvakal",
      "Pattikonda",
      "Pedda Kadubur",
      "Tuggali",
      "Veldurthy",
      "Yemmiganur"
    ],
    "Nandyal": [
      "Allagadda",
      "Atmakur",
      "Banaganapalli",
      "Bandi Atmakur",
      "Bethamcherla",
      "Chagalamarri",
      "Dhone",
      "Dornipadu",
      "Gadivemula",
      "Gospadu",
      "Jupadu Bunglow",
      "Koilakuntla",
      "Kolimigundla",
      "Kothapalle",
      "Mahanandi",
      "Midthur",
      "Nandikotkur",
      "Nandyal Rural",
      "Nandyal Urban",
      "Owk",
      "Pagidyala",
      "Pamulapadu",
      "Panyam",
      "Peapully",
      "Rudravaram",
      "Sanjamala",
      "Sirvel",
      "Srisailam",
      "Uyyalawada",
      "Velugodu"
    ],
    "Ntr": [
      "Atlapragada Konduru",
      "Chandarlapadu",
      "Gaddamanugu Konduru",
      "Gampalagudem",
      "Ibrahimpatnam",
      "Jaggaiahpeta",
      "Kanchikacherla",
      "Mylavaram",
      "Nandigama",
      "Penuganchiprolu",
      "Reddigudem",
      "Tiruvuru",
      "Vatsavai",
      "Veerullapadu",
      "Vijayawada (Rural)",
      "Vijayawada Central",
      "Vijayawada East",
      "Vijayawada North",
      "Vijayawada West",
      "Vissannapeta"
    ],
    "Palnadu": [
      "Amaravathi",
      "Atchampet",
      "Bellamkonda",
      "Bollapalli",
      "Chilakaluripet H/O.Purushotha Patnam",
      "Dachepalli",
      "Durgi",
      "Edlapadu",
      "Gurajala",
      "Ipuru",
      "Karempudi",
      "Krosuru",
      "Machavaram",
      "Macherla",
      "Muppalla",
      "Nadendla",
      "Narasaraopet",
      "Nekarikallu",
      "Nuzendla",
      "Pedakurapadu",
      "Piduguralla",
      "Rajupalem",
      "Rentachintala",
      "Rompicharla",
      "Sattenapalli",
      "Savalyapuram H/O Kanamarlapudi",
      "Veldurthy",
      "Vinukonda"
    ],
    "Parvathipuram Manyam": [
      "Balijipeta",
      "Bhamini",
      "Garugubilli",
      "Gummalakshmipuram",
      "Jiyyammavalasa",
      "Komarada",
      "Kurupam",
      "Makkuva",
      "Pachipenta",
      "Palakonda",
      "Parvathipuram",
      "Salur",
      "Seethampeta",
      "Seethanagaram",
      "Veeraghattam"
    ],
    "Prakasam": [
      "Ardhaveedu",
      "Bestavaripeta",
      "Chandra Sekhara Puram",
      "Chimakurthy",
      "Cumbum",
      "Darsi",
      "Donakonda",
      "Dornala",
      "Giddalur",
      "Hanumanthuni Padu",
      "Kanigiri",
      "Komarolu",
      "Konakanamitla",
      "Kondapi",
      "Kotha Patnam",
      "Kurichedu",
      "Maddipadu",
      "Markapuram",
      "Marripudi",
      "Mundlamuru",
      "Naguluppala Padu",
      "Ongole Rural",
      "Ongole Urban",
      "Pamur",
      "Pedacherlo Palle",
      "Peddaaraveedu",
      "Podili",
      "Ponnaluru",
      "Pullalacheruvu",
      "Racherla",
      "Santhanuthala Padu",
      "Singarayakonda",
      "Tangutur",
      "Tarlupadu",
      "Thallur",
      "Tripuranthakam",
      "Veligandla",
      "Yerragondapalem",
      "Zarugumalli"
    ],
    "Sri Potti Sriramulu Nellore": [
      "Allur",
      "Ananthasagaram",
      "Anumasamudrampeta",
      "Atmakur",
      "Bogole",
      "Buchireddipalem",
      "Chejerla",
      "Dagadarthi",
      "Duttalur",
      "Gudluru",
      "Indukurpet",
      "Jaladanki",
      "Kaligiri",
      "Kaluvoya",
      "Kandukuru",
      "Kavali",
      "Kodavalur",
      "Kondapuram",
      "Kovur",
      "Lingasamudram",
      "Manubolu",
      "Marripadu",
      "Muthukur",
      "Nellore Rural",
      "Nellore Urban",
      "Podalakur",
      "Rapur",
      "Sangam",
      "Seetharamapuram",
      "Sydapuram",
      "Vidavalur",
      "Vinjamur",
      "Voletivaripalem",
      "Thotapalligudur",
      "Udayagiri",
      "Ulavapadu",
      "Varikuntapadu",
      "Venkatachalam"
    ],
    "Sri Sathya Sai": [
      "Agali",
      "Amadagur",
      "Amarapuram",
      "Bathalapalli",
      "Bukkapatnam",
      "Chennekothapalli",
      "Chilamathur",
      "Dharmavaram",
      "Gandlapenta",
      "Gorantla",
      "Gudibanda",
      "Hindupur",
      "Kadiri",
      "Kanaganipalli",
      "Kothacheruvu",
      "Lepakshi",
      "Madakasira",
      "Mudigubba",
      "Nallachervu",
      "Nallamada",
      "Nambulapulakunta",
      "Obuladevaracheruvu",
      "Parigi",
      "Penukonda",
      "Puttaparthy",
      "Ramagiri",
      "Roddam",
      "Rolla",
      "Somandepalli",
      "Tadimarri",
      "Talupula",
      "Tanakal"
    ],
    "Srikakulam": [
      "Amadalavalasa",
      "Burja",
      "Etcherla",
      "Ganguvarisigadam",
      "Gara",
      "Hiramandalam",
      "Ichchapuram",
      "Jalumuru",
      "Kanchili",
      "Kaviti",
      "Kotabommali",
      "Kothuru",
      "Laveru",
      "Laxminarasupeta",
      "Mandasa",
      "Meliaputti",
      "Nandigam",
      "Narasannapeta",
      "Palasa",
      "Pathapatnam",
      "Polaki",
      "Ponduru",
      "Ranastalam",
      "Santhabommali",
      "Saravakota",
      "Sarubujjili",
      "Sompeta",
      "Srikakulam",
      "Tekkali",
      "Vajrapukotturu"
    ],
    "Tirupati": [
      "Balayapalli",
      "Buchinaidu Kandriga",
      "Chandragiri",
      "Chilamathur",
      "Erpedu",
      "K.V.B.Puram",
      "Nagalapuram",
      "Narayanavanam",
      "Pakala",
      "Pellakur",
      "Renigunta",
      "Satyavedu",
      "Srikalahasti",
      "Thottambedu",
      "Tirupati (Rural)",
      "Tirupati (Urban)",
      "Vadamalapeta",
      "Varadaiahpalem",
      "Venkatagiri",
      "Yerpedu"
    ],
    "Visakhapatnam": [
      "Anakapalle",
      "Bheemunipatnam",
      "Gajuwaka",
      "Munagapaka",
      "Paravada",
      "Pedagantyada",
      "Pendurthi",
      "Visakhapatnam (Rural)",
      "Visakhapatnam (Urban)"
    ],
    "Vizianagaram": [
      "Bobbili",
      "Bondapalli",
      "Cheepurupalle",
      "Dattirajeru",
      "Denkada",
      "Garividi",
      "Gajapathinagaram",
      "Gurla",
      "Jami",
      "Kothavalasa",
      "Lakkavarapukota",
      "Mentada",
      "Merakamudidam",
      "Nellimarla",
      "Pusapatirega",
      "Ramabhadrapuram",
      "Srungavarapukota",
      "Therlam",
      "Vepada",
      "Vizianagaram"
    ],
    "West Godavari": [
      "Achanta",
      "Akiveedu",
      "Attili",
      "Bhimavaram",
      "Bhimadole",
      "Buttayagudem",
      "Chagallu",
      "Devarapalli",
      "Denduluru",
      "Ganapavaram",
      "Kalla",
      "Kovvur",
      "Mogalthur",
      "Nidadavolu",
      "Narsapur",
      "Nallajerla",
      "Palakoderu",
      "Palakol",
      "Pentapadu",
      "Penugonda",
      "Penumantra",
      "Peravali",
      "Poduru",
      "Polavaram",
      "Tanuku",
      "Tadepalligudem",
      "Undi",
      "Undrajavaram",
      "Veeravasaram",
      "Yelamanchili"
    ],
    "Y.S.R. Kadapa": [
      "Atlur",
      "Badvel",
      "Brahmamgarimattam",
      "Chapadu",
      "Chennur",
      "Chinnamandem",
      "Chitvel",
      "Duvvur",
      "Galiveedu",
      "Gopavaram",
      "Jammalamadugu",
      "Kalabairavapattnam",
      "Khajipet",
      "Kodur",
      "Kondapuram",
      "Kalasapadu",
      "Muddanur",
      "Mydukur",
      "Peddamudium",
      "Pendlimarri",
      "Proddatur",
      "Rajupalem",
      "Ramapuram",
      "S.Mydukur",
      "Sidhout",
      "Thondur",
      "Vallur",
      "Veeraballe",
      "Vempalle",
      "Vontimitta"
    ]
  },


  "Arunachal Pradesh": {
    "Tawang": ["Tawang", "Bumla"],
    "West Kameng": ["Bomdila", "Rupa"],
    "East Kameng": ["Seppa", "Sangram"],
    "Lower Subansiri": ["Ziro", "Daporijo"],
    "Papum Pare": ["Itanagar", "Naharlagun"],
    "Upper Subansiri": ["Daporijo", "Margherita"]
  },
  "Bihar": {
    "Patna": ["Patna", "Danapur"],
    "Gaya": ["Gaya", "Bodh Gaya"],
    "Bhagalpur": ["Bhagalpur", "Naugachia"],
    "Muzaffarpur": ["Muzaffarpur", "Sahebganj"],
    "Darbhanga": ["Darbhanga", "Jhaijha"],
    "Purnia": ["Purnia", "Kishanganj"]
  },
  "Chhattisgarh": {
    "Raipur": ["Raipur", "Durg"],
    "Bilaspur": ["Bilaspur", "Masturi"],
    "Korba": ["Korba", "Katghora"],
    "Durg": ["Durg", "Bhilai"],
    "Rajnandgaon": ["Rajnandgaon", "Dongargaon"]
  },
  "Delhi": {
    "Central": ["Connaught Place", "Karol Bagh"],
    "East": ["Preet Vihar", "Laxmi Nagar"],
    "New Delhi": ["Chanakyapuri", "Sarojini Nagar"],
    "North": ["Civil Lines", "Model Town"],
    "North East": ["Seelampur", "Shahdara"],
    "North West": ["Pitampura", "Rohini"],
    "Shahdara": ["Dilshad Garden", "Karkardooma"],
    "South": ["Greater Kailash", "Lajpat Nagar"],
    "South East": ["Kalkaji", "Nehru Place"],
    "South West": ["Dwarka", "Vasant Kunj"],
    "West": ["Janakpuri", "Rajouri Garden"]
  },
  "Gujarat": {
    "Ahmedabad": ["Ahmedabad City", "Vastrapur"],
    "Vadodara": ["Vadodara City", "Fatehganj"],
    "Surat": ["Surat City", "Udhna"],
    "Rajkot": ["Rajkot City", "Jasdan"],
    "Gandhinagar": ["Gandhinagar City", "Mansa"]
  },

  "Himachal Pradesh": {
    "Bilaspur": [
      "Bharari",
      "Bilaspur Sadar",
      "Ghumarwin",
      "Jhanduta",
      "Kalol",
      "Naina Devi",
      "Namhol"
    ],
    "Chamba": [
      "Bhalai",
      "Bharmour",
      "Bhattiyat",
      "Chamba",
      "Churah",
      "Dalhousie",
      "Dharwala",
      "Holi",
      "Kakira",
      "Pangi",
      "Pukhri",
      "Saho",
      "Saluni",
      "Sihunta",
      "Telka"
    ],
    "Hamirpur": [
      "Barsar",
      "Bhoranj",
      "Bhota",
      "Dhatwal",
      "Galore",
      "Hamirpur",
      "Jahu",
      "Kangoo",
      "Lambloo",
      "Nadaun",
      "Tauni Devi Bamson",
      "Tira Sujanpur"
    ],
    "Kangra": [
      "Alampur",
      "Baijnath",
      "Baroh",
      "Bharoli",
      "Bhawarna",
      "Chadiyar",
      "Dadasiba",
      "Dareeni",
      "Dehra Gopipur",
      "Dharmsala",
      "Dhira",
      "Fatehpur",
      "Gangath",
      "Harchakian",
      "Haripur",
      "Indora",
      "Jaisinghpur",
      "Jaswan",
      "Jawalamukhi",
      "Jawali",
      "Kangra",
      "Khundian",
      "Kotla",
      "Lagru",
      "Majheen",
      "Multhan",
      "Nagrota Bagwan",
      "Nagrota Surian",
      "Nurpur",
      "Palampur",
      "Panchrukhi",
      "Pragpur",
      "Raja Ka Talab",
      "Rakkar",
      "Rey",
      "Sadwan",
      "Shahpur",
      "Sulah",
      "Thakurdwara",
      "Thural"
    ],
    "Kinnaur": [
      "Hangrang",
      "Kalpa",
      "Morang",
      "Nichar",
      "Poo",
      "Sangla",
      "Tapri"
    ],
    "Kullu": [
      "Ani",
      "Banjar",
      "Bhuntar",
      "Jari",
      "Kullu",
      "Manali",
      "Nirmand",
      "Nither",
      "Sainj"
    ],
    "Lahaul and Spiti": [
      "Lahul",
      "Spiti",
      "Udaipur"
    ],
    "Mandi": [
      "Aut",
      "Bagachnogi",
      "Bagshad",
      "Baldwara",
      "Balh",
      "Bali Chowki",
      "Bhadrota",
      "Chachyot",
      "Chhatri",
      "Dehar",
      "Dhalwan",
      "Dharmpur",
      "Jogindarnagar",
      "Karsog",
      "Katoula",
      "Kotli",
      "Lad Bharol",
      "Makridi",
      "Mandap",
      "Mandi",
      "Nihri",
      "Padhar",
      "Pangna",
      "Rewalsar",
      "Sandhol",
      "Sarkaghat",
      "Sundarnagar",
      "Thachi",
      "Thunag",
      "Tihra",
      "Tikken"
    ],
    "Shimla": [
      "Chaupal",
      "Chirgaon",
      "Deha",
      "Dhami",
      "Dodra Kwar",
      "Jalog",
      "Jangla",
      "Jubbal",
      "Junga",
      "Kalbog",
      "Kotgarh",
      "Kotkhai",
      "Kumarsain",
      "Kupvi",
      "Nankhari",
      "Nerwa",
      "Rampur",
      "Rohru",
      "Sarahan",
      "Sarawati Nagar",
      "Shimla (Rural)",
      "Shimla (Urban)",
      "Sunni",
      "Taklech",
      "Theog",
      "Tikar"
    ],
    "Sirmaur": [
      "Dadahu",
      "Haripurdhar",
      "Kamrau",
      "Majra",
      "Nahan",
      "Narag",
      "Nohra",
      "Pachhad",
      "Pajhota",
      "Paonta Sahib",
      "Rajgarh",
      "Renuka",
      "Ronhat",
      "Shillai"
    ],
    "Solan": [
      "Arki",
      "Baddi",
      "Darlaghat",
      "Kandaghat",
      "Kasauli",
      "Krishangarh",
      "Kunihar",
      "Loharghat",
      "Mamlig",
      "Nalagarh",
      "Panjehra",
      "Parwanoo",
      "Ramshahr",
      "Solan"
    ],
    "Una": [
      "Amb",
      "Bangana",
      "Bharwain",
      "Birhu Kalan",
      "Dulahar",
      "Gagret",
      "Ghanari",
      "Haroli",
      "Ispur",
      "Jol",
      "Mehatpur",
      "Una"
    ]
  },

  "Jharkhand": {
    "Bokaro": ["Bokaro Steel City", "Chas"],
    "Dhanbad": ["Dhanbad City", "Sindri"],
    "East Singhbhum": ["Jamshedpur", "Ghatshila"],
    "Deoghar": ["Deoghar City", "Madhupur"],
    "Ranchi": ["Ranchi City", "Ramgarh"]
  },
  "Karnataka": {
    "Bangalore": ["Bangalore City", "Malleswaram"],
    "Mysore": ["Mysore City", "Hunsur"],
    "Mangalore": ["Mangalore City", "Surathkal"],
    "Hubli": ["Hubli City", "Dharwad"],
    "Belgaum": ["Belgaum City", "Khanapur"]
  },
  "Kerala": {
    "Thiruvananthapuram": ["Thiruvananthapuram City", "Kazhakootam"],
    "Kochi": ["Kochi City", "Ernakulam"],
    "Kozhikode": ["Kozhikode City", "Koyilandy"],
    "Malappuram": ["Malappuram City", "Perinthalmanna"],
    "Kottayam": ["Kottayam City", "Changanassery"]
  },
  "Madhya Pradesh": {
    "Indore": ["Indore City", "Mhow"],
    "Bhopal": ["Bhopal City", "Hoshangabad"],
    "Gwalior": ["Gwalior City", "Morena"],
    "Jabalpur": ["Jabalpur City", "Katangi"],
    "Ujjain": ["Ujjain City", "Madhav Nagar"]
  },
  "Maharashtra": {
    "Mumbai": ["Mumbai City", "Thane"],
    "Pune": ["Pune City", "Khadki"],
    "Nagpur": ["Nagpur City", "Kamptee"],
    "Nashik": ["Nashik City", "Sinnar"],
    "Aurangabad": ["Aurangabad City", "Kannad"]
  },
  "Manipur": {
    "Imphal East": ["Imphal City", "Wangoi"],
    "Imphal West": ["Imphal City", "Lilong"],
    "Thoubal": ["Thoubal City", "Kakching"],
    "Bishnupur": ["Bishnupur City", "Nambol"],
    "Chandel": ["Chandel City", "Moreh"]
  },
  "Meghalaya": {
    "East Khasi Hills": ["Shillong", "Jowai"],
    "West Khasi Hills": ["Nongstoin", "Mairang"],
    "Ri Bhoi": ["Nongpoh", "Umiam"],
    "East Garo Hills": ["Williamnagar", "Babadam"],
    "West Garo Hills": ["Tura", "Rongram"]
  },
  "Mizoram": {
    "Aizawl": ["Aizawl City", "Saitual"],
    "Champhai": ["Champhai City", "Hnahthial"],
    "Serchhip": ["Serchhip City", "Lunglei"],
    "Lunglei": ["Lunglei City", "Tlabung"],
    "Mamit": ["Mamit City", "Kawrthah"]
  },
  "Nagaland": {
    "Dimapur": ["Dimapur City", "Chümoukedima"],
    "Kohima": ["Kohima City", "Phek"],
    "Mon": ["Mon City", "Longleng"],
    "Zunheboto": ["Zunheboto City", "Satoi"],
    "Wokha": ["Wokha City", "Bhandari"]
  },
  "Odisha": {
    "Bhubaneswar": ["Bhubaneswar City", "Khurda"],
    "Cuttack": ["Cuttack City", "Jagatpur"],
    "Sambalpur": ["Sambalpur City", "Burla"],
    "Berhampur": ["Berhampur City", "Brahmapur"],
    "Rourkela": ["Rourkela City", "Birmitrapur"]
  },
  "Punjab": {
    "Amritsar": ["Amritsar City", "Tarn Taran"],
    "Ludhiana": ["Ludhiana City", "Jagraon"],
    "Patiala": ["Patiala City", "Rajpura"],
    "Jalandhar": ["Jalandhar City", "Phagwara"],
    "Mohali": ["Mohali City", "Kharar"]
  },
  "Rajasthan": {
    "Jaipur": ["Jaipur City", "Sanganer"],
    "Udaipur": ["Udaipur City", "Rajsamand"],
    "Jodhpur": ["Jodhpur City", "Osian"],
    "Ajmer": ["Ajmer City", "Kishangarh"],
    "Bikaner": ["Bikaner City", "Pugal"]
  },
  "Tamil Nadu": {
    "Chennai": ["Chennai City", "T Nagar"],
    "Coimbatore": ["Coimbatore City", "Tidel Park"],
    "Madurai": ["Madurai City", "Thiruparankundram"],
    "Tiruchirappalli": ["Tiruchirappalli City", "Srirangam"],
    "Salem": ["Salem City", "Attur"]
  },
  "Telangana": {
    "Hyderabad": ["Hyderabad City", "Secunderabad"],
    "Warangal": ["Warangal City", "Kazipet"],
    "Nizamabad": ["Nizamabad City", "Bodhan"],
    "Khammam": ["Khammam City", "Kothagudem"],
    "Mahabubnagar": ["Mahabubnagar City", "Kurgunta"]
  },
  "Tripura": {
    "Agartala": ["Agartala City", "Udaipur"],
    "Dhalai": ["Ambassa", "Manu"],
    "North Tripura": ["Dharmanagar", "Kailashahar"],
    "Unakoti": ["Kailashahar", "Panchayatan"],
    "South Tripura": ["Belonia", "Sabroom"]
  },
  "Uttar Pradesh": {
    "Agra": ["Agra City", "Firozabad"],
    "Lucknow": ["Lucknow City", "Barabanki"],
    "Varanasi": ["Varanasi City", "Mirzapur"],
    "Kanpur": ["Kanpur City", "Unnao"],
    "Noida": ["Noida City", "Greater Noida"]
  },
  "Uttarakhand": {
    "Dehradun": ["Dehradun City", "Rishikesh"],
    "Haridwar": ["Haridwar City", "Roorkee"],
    "Nainital": ["Nainital City", "Haldwani"],
    "Pauri Garhwal": ["Pauri City", "Lansdowne"],
    "Tehri Garhwal": ["Tehri City", "New Tehri"]
  },
  "West Bengal": {
    "Kolkata": ["Kolkata City", "Howrah"],
    "Darjeeling": ["Darjeeling City", "Kalimpong"],
    "Siliguri": ["Siliguri City", "Jalpaiguri"],
    "Malda": ["Malda City", "Baharampur"],
    "North 24 Parganas": ["Barasat", "Bongaon"]
  }
};