export const stateDistrictCityData = {
  "Andaman and Nicobar Islands": {
    "Nicobars": [
      "Car Nicobar",
      "Great Nicobar",
      "Nancowry"
    ],
    "North and Middle Andaman": [
      "Diglipur",
      "Mayabunder",
      "Rangat"
    ],
    "South Andamans": [
      "Ferrargunj",
      "Little Andaman",
      "Port Blair"
    ]
  },

  "Andhra Pradesh": {
    "Alluri Sitharama Raju": [
      "Addateegala",
      "Ananthagiri",
      "Araku Valley",
      "Chinthapalli",
      "Chinturu",
      "Devipatnam",
      "Dumbriguda",
      "G.Madugula",
      "Gangavaram",
      "Gudem Kotha Veedhi",
      "Hukumpeta",
      "Koyyuru",
      "Kunavaram",
      "Maredumilli",
      "Munchingi Puttu",
      "Paderu",
      "Peda Bayalu",
      "Rajavommangi",
      "Rampachodavaram",
      "Vararamachandrapuram",
      "Y. Ramavaram",
      "Yetapaka"
    ],
    "Anakapalli": [
      "Anakapalli",
      "Atchuthapuram",
      "Butchayyapeta",
      "Cheedikada",
      "Chodavaram",
      "Devarapalli",
      "Golugonda",
      "K.Kotapadu",
      "Kasimkota",
      "Kotauratla",
      "Madugula",
      "Makavarapalem",
      "Munagapaka",
      "Nakkapalli",
      "Narsipatnam",
      "Nathavaram",
      "Paravada",
      "Payakaraopeta",
      "Rambilli",
      "Ravikamatham",
      "Rolugunta",
      "S.Rayavaram",
      "Sabbavaram",
      "Yelamanchili"
    ],
    "Ananthapuramu": [
      "Anantapur Rural",
      "Anantapur Urban",
      "Atmakur",
      "Beluguppa",
      "Bommanahal",
      "Brahmasamudram",
      "Bukkaraya Samudram",
      "D.Hirehal",
      "Garladinne",
      "Gooty",
      "Gummagatta",
      "Guntakal",
      "Kalyanadurg",
      "Kambadur",
      "Kanekal",
      "Kudair",
      "Kundurpi",
      "Narpala",
      "Pamidi",
      "Peddapappur",
      "Peddavaduguru",
      "Putlur",
      "Rapthadu",
      "Rayadurg",
      "Settur",
      "Singanamala",
      "Tadipatri",
      "Uravakonda",
      "Vajrakarur",
      "Vidapanakal",
      "Yadiki",
      "Yellanur"
    ],
    "Annamayya": [
      "Beerongi Kothakota",
      "Chinnamandem",
      "Chitvel",
      "Galiveedu",
      "Gurramkonda",
      "Kalakada",
      "Kalikiri",
      "Kambhamvaripalle",
      "Kodur",
      "Kurabalakota",
      "Lakkireddipalli",
      "Madanapalle",
      "Mulakalacheruvu",
      "Nandalur",
      "Nimmanapalle",
      "Obulavaripalle",
      "Pedda Thippasamudram",
      "Peddamandyam",
      "Penagalur",
      "Pileru",
      "Pullampeta",
      "Rajampet",
      "Ramapuram",
      "Ramasamudram",
      "Rayachoti",
      "Sambepalle",
      "T.Sundupalle",
      "Thamballapalle",
      "Valmikipuram",
      "Veeraballe"
    ],
    "Bapatla": [
      "Addanki",
      "Amarthalur",
      "Ballikurava",
      "Bapatla",
      "Bhattiprolu",
      "Cherukupalli",
      "Chinaganjam",
      "Chirala",
      "Inkollu",
      "J.Pangulur",
      "Karamchedu",
      "Karlapalem",
      "Kolluru",
      "Korisapadu",
      "Martur",
      "Nagaram",
      "Nizampatnam",
      "Parchur",
      "Pittalavanipalem",
      "Repalle",
      "Santhamaguluru",
      "Tsunduru",
      "Vemuru",
      "Vetapalem",
      "Yeddana Pudi"
    ],
    "Chittoor": [
      "Baireddipalle",
      "Bangarupalem",
      "Chittoor Rural",
      "Chittoor Urban",
      "Chowdepalle",
      "Gangadhara Nellore",
      "Gangavaram",
      "Gudipala",
      "Gudupalle",
      "Irala",
      "Karvetinagar",
      "Kuppam",
      "Nagari",
      "Nindra",
      "Palamaner",
      "Palasamudram",
      "Peddapanjani",
      "Penumur",
      "Pulicherla",
      "Punganuru",
      "Puthalapattu",
      "Ramakuppam",
      "Rompicherla",
      "Santhipuram",
      "Sodam",
      "Vijayapuram",
      "Yadamarri",
      "Somala",
      "Srirangarajapuram",
      "Thavanampalle",
      "Vedurukuppam",
      "Venkatagirikota"
    ],
    "Dr. B.R. Ambedkar Konaseema": [
      "Ainavilli",
      "Alamuru",
      "Allavaram",
      "Amalapuram",
      "Ambajipeta",
      "Atreyapuram",
      "I. Polavaram",
      "K Gangavaram",
      "Kapileswarapuram",
      "Katrenikona",
      "Kothapeta",
      "Malikipuram",
      "Mamidikuduru",
      "Mandapeta",
      "Mummidivaram",
      "P.Gannavaram",
      "Ramachandrapuram",
      "Ravulapalem",
      "Rayavaram",
      "Razole",
      "Sakhinetipalli",
      "Uppalaguptam"
    ],
    "East Godavari": [
      "Anaparthi",
      "Biccavolu",
      "Chagallu",
      "Devarapalle",
      "Gokavaram",
      "Gopalapuram",
      "Kadiam",
      "Korukonda",
      "Kovvur",
      "Nallajerla",
      "Nidadavole",
      "Peravali",
      "Rajamahendravaram Rural",
      "Rajamahendravaram Urban",
      "Rajanagaram",
      "Rangampeta",
      "Seethanagaram",
      "Tallapudi",
      "Undrajavaram"
    ],
    "Eluru": [
      "Agiripalli",
      "Bheemadole",
      "Buttayagudem",
      "Chatrai",
      "Chintalapudi",
      "Denduluru",
      "Dwarakatirumala",
      "Eluru Rural",
      "Eluru Urban",
      "Jangareddigudem",
      "Jeelugu Milli",
      "Kaikaluru",
      "Kalidindi",
      "Kamavarapukota",
      "Koyyalagudem",
      "Kukunoor",
      "Lingapalem",
      "Mandavalli",
      "Mudinepalle",
      "Musunuru",
      "Nidamarru",
      "Nuzividu",
      "Pedapadu",
      "Pedavegi",
      "Polavaram",
      "T.Narasapuram",
      "Unguturu",
      "Velairpadu"
    ],
    "Guntur": [
      "Chebrolu",
      "Duggirala",
      "Guntur East",
      "Guntur West",
      "Kakumanu",
      "Kollipara",
      "Mangalagiri",
      "Medikonduru",
      "Pedakakani",
      "Pedanandipadu",
      "Phirangipuram",
      "Ponnur",
      "Prathipadu",
      "Tadepalli",
      "Tadikonda",
      "Tenali",
      "Thulluru",
      "Vatticherukuru"
    ],
    "Kakinada": [
      "Gandepalli",
      "Gollaprolu",
      "Jaggampeta",
      "Kajuluru",
      "Kakinada (Rural)",
      "Kakinada (Urban)",
      "Karapa",
      "Kirlampudi",
      "Kotananduru",
      "Pedapudi",
      "Peddapuram",
      "Pithapuram",
      "Prathipadu",
      "Rowthulapudi",
      "Samalkota",
      "Sankhavaram",
      "Tallarevu",
      "Thondangi",
      "Tuni",
      "U.Kothapalli",
      "Yeleswaram"
    ],
    "Krishna": [
      "Avanigadda",
      "Bantumilli",
      "Bapulapadu",
      "Challapalli",
      "Gannavaram",
      "Ghantasala",
      "Gudivada",
      "Gudlavalleru",
      "Guduru",
      "Kankipadu",
      "Koduru",
      "Kruthivennu",
      "Machilipatnam North",
      "Machilipatnam South",
      "Mopidevi",
      "Movva",
      "Nagayalanka",
      "Nandivada",
      "Pamarru",
      "Pamidimukkala",
      "Pedana",
      "Pedaparupudi",
      "Penamaluru",
      "Thotlavalluru",
      "Unguturu",
      "Vuyyuru"
    ],
    "Kurnool": [
      "Adoni",
      "Alur",
      "Aspari",
      "C.Belagal",
      "Chippagiri",
      "Devanakonda",
      "Gonegandla",
      "Gudur",
      "Halaharvi",
      "Holagunda",
      "Kallur",
      "Kodumur",
      "Kosigi",
      "Kowthalam",
      "Krishnagiri",
      "Kurnool Rural",
      "Kurnool Urban",
      "Maddikera (East)",
      "Mantralayam",
      "Nandavaram",
      "Orvakal",
      "Pattikonda",
      "Pedda Kadubur",
      "Tuggali",
      "Veldurthy",
      "Yemmiganur"
    ],
    "Nandyal": [
      "Allagadda",
      "Atmakur",
      "Banaganapalli",
      "Bandi Atmakur",
      "Bethamcherla",
      "Chagalamarri",
      "Dhone",
      "Dornipadu",
      "Gadivemula",
      "Gospadu",
      "Jupadu Bunglow",
      "Koilakuntla",
      "Kolimigundla",
      "Kothapalle",
      "Mahanandi",
      "Midthur",
      "Nandikotkur",
      "Nandyal Rural",
      "Nandyal Urban",
      "Owk",
      "Pagidyala",
      "Pamulapadu",
      "Panyam",
      "Peapully",
      "Rudravaram",
      "Sanjamala",
      "Sirvel",
      "Srisailam",
      "Uyyalawada",
      "Velugodu"
    ],
    "Ntr": [
      "Atlapragada Konduru",
      "Chandarlapadu",
      "Gaddamanugu Konduru",
      "Gampalagudem",
      "Ibrahimpatnam",
      "Jaggaiahpeta",
      "Kanchikacherla",
      "Mylavaram",
      "Nandigama",
      "Penuganchiprolu",
      "Reddigudem",
      "Tiruvuru",
      "Vatsavai",
      "Veerullapadu",
      "Vijayawada (Rural)",
      "Vijayawada Central",
      "Vijayawada East",
      "Vijayawada North",
      "Vijayawada West",
      "Vissannapeta"
    ],
    "Palnadu": [
      "Amaravathi",
      "Atchampet",
      "Bellamkonda",
      "Bollapalli",
      "Chilakaluripet H/O.Purushotha Patnam",
      "Dachepalli",
      "Durgi",
      "Edlapadu",
      "Gurajala",
      "Ipuru",
      "Karempudi",
      "Krosuru",
      "Machavaram",
      "Macherla",
      "Muppalla",
      "Nadendla",
      "Narasaraopet",
      "Nekarikallu",
      "Nuzendla",
      "Pedakurapadu",
      "Piduguralla",
      "Rajupalem",
      "Rentachintala",
      "Rompicharla",
      "Sattenapalli",
      "Savalyapuram H/O Kanamarlapudi",
      "Veldurthy",
      "Vinukonda"
    ],
    "Parvathipuram Manyam": [
      "Balijipeta",
      "Bhamini",
      "Garugubilli",
      "Gummalakshmipuram",
      "Jiyyammavalasa",
      "Komarada",
      "Kurupam",
      "Makkuva",
      "Pachipenta",
      "Palakonda",
      "Parvathipuram",
      "Salur",
      "Seethampeta",
      "Seethanagaram",
      "Veeraghattam"
    ],
    "Prakasam": [
      "Ardhaveedu",
      "Bestavaripeta",
      "Chandra Sekhara Puram",
      "Chimakurthy",
      "Cumbum",
      "Darsi",
      "Donakonda",
      "Dornala",
      "Giddalur",
      "Hanumanthuni Padu",
      "Kanigiri",
      "Komarolu",
      "Konakanamitla",
      "Kondapi",
      "Kotha Patnam",
      "Kurichedu",
      "Maddipadu",
      "Markapuram",
      "Marripudi",
      "Mundlamuru",
      "Naguluppala Padu",
      "Ongole Rural",
      "Ongole Urban",
      "Pamur",
      "Pedacherlo Palle",
      "Peddaaraveedu",
      "Podili",
      "Ponnaluru",
      "Pullalacheruvu",
      "Racherla",
      "Santhanuthala Padu",
      "Singarayakonda",
      "Tangutur",
      "Tarlupadu",
      "Thallur",
      "Tripuranthakam",
      "Veligandla",
      "Yerragondapalem",
      "Zarugumalli"
    ],
    "Sri Potti Sriramulu Nellore": [
      "Allur",
      "Ananthasagaram",
      "Anumasamudrampeta",
      "Atmakur",
      "Bogole",
      "Buchireddipalem",
      "Chejerla",
      "Dagadarthi",
      "Duttalur",
      "Gudluru",
      "Indukurpet",
      "Jaladanki",
      "Kaligiri",
      "Kaluvoya",
      "Kandukuru",
      "Kavali",
      "Kodavalur",
      "Kondapuram",
      "Kovur",
      "Lingasamudram",
      "Manubolu",
      "Marripadu",
      "Muthukur",
      "Nellore Rural",
      "Nellore Urban",
      "Podalakur",
      "Rapur",
      "Sangam",
      "Seetharamapuram",
      "Sydapuram",
      "Vidavalur",
      "Vinjamur",
      "Voletivaripalem",
      "Thotapalligudur",
      "Udayagiri",
      "Ulavapadu",
      "Varikuntapadu",
      "Venkatachalam"
    ],
    "Sri Sathya Sai": [
      "Agali",
      "Amadagur",
      "Amarapuram",
      "Bathalapalli",
      "Bukkapatnam",
      "Chennekothapalli",
      "Chilamathur",
      "Dharmavaram",
      "Gandlapenta",
      "Gorantla",
      "Gudibanda",
      "Hindupur",
      "Kadiri",
      "Kanaganipalli",
      "Kothacheruvu",
      "Lepakshi",
      "Madakasira",
      "Mudigubba",
      "Nallachervu",
      "Nallamada",
      "Nambulapulakunta",
      "Obuladevaracheruvu",
      "Parigi",
      "Penukonda",
      "Puttaparthy",
      "Ramagiri",
      "Roddam",
      "Rolla",
      "Somandepalli",
      "Tadimarri",
      "Talupula",
      "Tanakal"
    ],
    "Srikakulam": [
      "Amadalavalasa",
      "Burja",
      "Etcherla",
      "Ganguvarisigadam",
      "Gara",
      "Hiramandalam",
      "Ichchapuram",
      "Jalumuru",
      "Kanchili",
      "Kaviti",
      "Kotabommali",
      "Kothuru",
      "Laveru",
      "Laxminarasupeta",
      "Mandasa",
      "Meliaputti",
      "Nandigam",
      "Narasannapeta",
      "Palasa",
      "Pathapatnam",
      "Polaki",
      "Ponduru",
      "Ranastalam",
      "Santhabommali",
      "Saravakota",
      "Sarubujjili",
      "Sompeta",
      "Srikakulam",
      "Tekkali",
      "Vajrapukotturu"
    ],
    "Tirupati": [
      "Balayapalli",
      "Buchinaidu Kandriga",
      "Chandragiri",
      "Chilamathur",
      "Erpedu",
      "K.V.B.Puram",
      "Nagalapuram",
      "Narayanavanam",
      "Pakala",
      "Pellakur",
      "Renigunta",
      "Satyavedu",
      "Srikalahasti",
      "Thottambedu",
      "Tirupati (Rural)",
      "Tirupati (Urban)",
      "Vadamalapeta",
      "Varadaiahpalem",
      "Venkatagiri",
      "Yerpedu"
    ],
    "Visakhapatnam": [
      "Anakapalle",
      "Bheemunipatnam",
      "Gajuwaka",
      "Munagapaka",
      "Paravada",
      "Pedagantyada",
      "Pendurthi",
      "Visakhapatnam (Rural)",
      "Visakhapatnam (Urban)"
    ],
    "Vizianagaram": [
      "Bobbili",
      "Bondapalli",
      "Cheepurupalle",
      "Dattirajeru",
      "Denkada",
      "Garividi",
      "Gajapathinagaram",
      "Gurla",
      "Jami",
      "Kothavalasa",
      "Lakkavarapukota",
      "Mentada",
      "Merakamudidam",
      "Nellimarla",
      "Pusapatirega",
      "Ramabhadrapuram",
      "Srungavarapukota",
      "Therlam",
      "Vepada",
      "Vizianagaram"
    ],
    "West Godavari": [
      "Achanta",
      "Akiveedu",
      "Attili",
      "Bhimavaram",
      "Bhimadole",
      "Buttayagudem",
      "Chagallu",
      "Devarapalli",
      "Denduluru",
      "Ganapavaram",
      "Kalla",
      "Kovvur",
      "Mogalthur",
      "Nidadavolu",
      "Narsapur",
      "Nallajerla",
      "Palakoderu",
      "Palakol",
      "Pentapadu",
      "Penugonda",
      "Penumantra",
      "Peravali",
      "Poduru",
      "Polavaram",
      "Tanuku",
      "Tadepalligudem",
      "Undi",
      "Undrajavaram",
      "Veeravasaram",
      "Yelamanchili"
    ],
    "Y.S.R. Kadapa": [
      "Atlur",
      "Badvel",
      "Brahmamgarimattam",
      "Chapadu",
      "Chennur",
      "Chinnamandem",
      "Chitvel",
      "Duvvur",
      "Galiveedu",
      "Gopavaram",
      "Jammalamadugu",
      "Kalabairavapattnam",
      "Khajipet",
      "Kodur",
      "Kondapuram",
      "Kalasapadu",
      "Muddanur",
      "Mydukur",
      "Peddamudium",
      "Pendlimarri",
      "Proddatur",
      "Rajupalem",
      "Ramapuram",
      "S.Mydukur",
      "Sidhout",
      "Thondur",
      "Vallur",
      "Veeraballe",
      "Vempalle",
      "Vontimitta"
    ]
  },


  "Arunachal Pradesh": {
    "Anjaw": ["Hawai", "Manchal", "Goiliang", "Hayuliang"],
    "Changlang": ["Changlang", "Bordumsa", "Diyun", "Kharsang", "Miao", "Namchik", "Nampong", "Vijaynagar"],
    "East Kameng": ["Seppa", "Bameng", "Bana", "Chayangtajo", "Pakke Kessang", "Pipu"],
    "East Siang": ["Pasighat", "Bilat", "Boleng", "Mebo", "Nari", "Pangin", "Ruksin"],
    "Kamle": ["Raga", "Damin", "Giba", "Lada", "Nyapin"],
    "Kra Daadi": ["Palin", "Chambang", "Damin", "Tali"],
    "Kurung Kumey": ["Koloriang", "Chayantajo", "Damin", "Nyapin", "Sarli"],
    "Lepa Rada": ["Along", "Basar", "Kamba", "Liromoba", "Tirbin"],
    "Lohit": ["Tezu", "Chowkham", "Lekang", "Namsai", "Sunpura", "Wakro"],
    "Longding": ["Longding", "Kanubari", "Pumao", "Tirap", "Wakka"],
    "Lower Dibang Valley": ["Roing", "Dambuk", "Hunli", "Koronu", "Meka", "Nizamghat"],
    "Lower Siang": ["Likabali", "Bame", "Kora", "Nari", "Sago"],
    "Lower Subansiri": ["Ziro", "Daporijo", "Bamin", "Duta", "Hija", "Joram", "Kimin", "Limeking", "Nacho", "Raga", "Taliha"],
    "Namsai": ["Namsai", "Chowkham", "Lekang", "Mahadevpur"],
    "Pakke Kessang": ["Seijosa", "Pakke Kessang"],
    "Papum Pare": ["Itanagar", "Naharlagun", "Balijan", "Banderdewa", "Doimukh", "Kimin", "Sagalee"],
    "Shi Yomi": ["Tato", "Mechuka", "Monigong"],
    "Siang": ["Boleng", "Pangin", "Rumgong"],
    "Tawang": ["Tawang", "Bumla", "Bongkhar", "Jang", "Kitpi", "Lumla", "Mukto"],
    "Tirap": ["Khonsa", "Borduria", "Deomali", "Lazu", "Niausa"],
    "Upper Dibang Valley": ["Anini", "Mipi", "Namdang", "Tahun"],
    "Upper Siang": ["Yingkiong", "Geku", "Jengging", "Katan", "Mariyang", "Mebo", "Nefra", "Tuting"],
    "Upper Subansiri": ["Daporijo", "Bamin", "Dumporijo", "Giba", "Limeking", "Nacho", "Siyum", "Taliha"],
    "West Kameng": ["Bomdila", "Rupa", "Bhalukpong", "Dirang", "Kalaktang", "Nafra", "Shergaon", "Thrizino"],
    "West Siang": ["Along", "Basar", "Kamba", "Liromoba", "Mechuka", "Rumgong", "Tirbin"]
  },

  "Assam": {
    "Bajali": ["Pathsala", "Barpeta Road", "Sarthebari"],
    "Baksa": ["Mushalpur", "Barama", "Baska", "Goreswar", "Nagrijuli", "Tamulpur"],
    "Barpeta": ["Barpeta", "Barpeta Road", "Chenga", "Jania", "Mandia", "Sarukhetri", "Sarthebari"],
    "Biswanath": ["Biswanath Chariali", "Behali", "Gohpur", "Sootea"],
    "Bongaigaon": ["Bongaigaon", "Bijni", "Boitamari", "Manikpur"],
    "Cachar": ["Silchar", "Barkhola", "Dholai", "Katigorah", "Lakhipur", "Sonai", "Udharbond"],
    "Charaideo": ["Sonari", "Amguri", "Mahmora"],
    "Chirang": ["Kajalgaon", "Bijni", "Borobazar", "Sidli"],
    "Darrang": ["Mangaldoi", "Dalgaon", "Kalaigaon", "Patacharkuchi", "Sipajhar"],
    "Dhemaji": ["Dhemaji", "Jonai", "Machkhowa", "Murkongselek", "Sissiborgaon"],
    "Dhubri": ["Dhubri", "Agomoni", "Bilasipara", "Chapar", "Gauripur", "Golakganj", "Mankachar", "Rupshi", "Sapatgram", "South Salmara"],
    "Dibrugarh": ["Dibrugarh", "Barbarua", "Chabua", "Jaipur", "Khowang", "Lahowal", "Moran", "Naharkatia", "Tingkhong"],
    "Dima Hasao": ["Haflong", "Diyungbra", "Harangajao", "Jatinga", "Mahur", "Maibong", "Umrangso"],
    "Goalpara": ["Goalpara", "Balijana", "Dudhnoi", "Jaleswar", "Krishnai", "Lakhipur", "Matia"],
    "Golaghat": ["Golaghat", "Bokakhat", "Dergaon", "Khumtai", "Sarupathar"],
    "Hailakandi": ["Hailakandi", "Algapur", "Catlicherra", "Lala"],
    "Hojai": ["Hojai", "Doboka", "Jugijan", "Lanka", "Lumding"],
    "Jorhat": ["Jorhat", "Jorhat East", "Jorhat West", "Mariani", "Titabor"],
    "Kamrup": ["Rangia", "Boko", "Chamaria", "Chhaygaon", "Goroimari", "Hajo", "Kamalpur", "Nagarbera", "Rani", "Sualkuchi"],
    "Kamrup Metropolitan": ["Guwahati", "Azara", "Chandrapur", "Dispur", "Jalukbari", "Sonapur"],
    "Karbi Anglong": ["Diphu", "Bokajan", "Hamren", "Howraghat", "Khatkhati", "Langsomepi", "Nilip", "Rongmongwe", "Samelangso"],
    "Karimganj": ["Karimganj", "Badarpur", "Nilambazar", "Patharkandi", "Ratabari", "Srikona"],
    "Kokrajhar": ["Kokrajhar", "Bhawraguri", "Dotma", "Gossaigaon", "Kachugaon", "Parbatjhora", "Sidli"],
    "Lakhimpur": ["North Lakhimpur", "Bihpuria", "Boginadi", "Dhakuakhana", "Ghilamara", "Kadam", "Narayanpur"],
    "Majuli": ["Majuli", "Garamur", "Jengraimukh"],
    "Morigaon": ["Morigaon", "Bhuragaon", "Jagiroad", "Laharighat", "Mayong"],
    "Nagaon": ["Nagaon", "Barhampur", "Batadrava", "Dhing", "Hojai", "Kaliabor", "Kampur", "Raha", "Rupahihat"],
    "Nalbari": ["Nalbari", "Barbhag", "Barkhetri", "Ghograpar", "Mukalmua", "Paschim Nalbari", "Tihu"],
    "Sivasagar": ["Sivasagar", "Amguri", "Demow", "Gaurisagar", "Nazira", "Sapekhati"],
    "Sonitpur": ["Tezpur", "Biswanath Chariali", "Bihaguri", "Borgolai", "Dhekiajuli", "Gabharu", "Helem", "Naduar", "Rangapara", "Sootea"],
    "South Salmara-Mankachar": ["Mankachar", "Rupshi", "South Salmara"],
    "Tinsukia": ["Tinsukia", "Digboi", "Doom Dooma", "Margherita", "Sadiya", "Saikhowa"],
    "Udalguri": ["Udalguri", "Bhergaon", "Dimakuchi", "Harisinga", "Kalaigaon", "Mazbat", "Rowta"],
    "West Karbi Anglong": ["Hamren", "Baithalangso", "Chinthong", "Rongram"]
  },

  "Bihar": {
    "Araria": ["Araria", "Forbesganj", "Jokihat", "Kursakanta", "Narpatganj", "Palasi", "Raniganj", "Sikti"],
    "Arwal": ["Arwal", "Kaler", "Kurtha", "Sonbhadra Banshi Suryapur"],
    "Aurangabad": ["Aurangabad", "Barun", "Daudnagar", "Deo", "Goh", "Haspura", "Kutumba", "Madanpur", "Nabinagar", "Obra", "Rafiganj"],
    "Banka": ["Banka", "Amarpur", "Barahat", "Belhar", "Bounsi", "Chandan", "Dhuraiya", "Fullidumar", "Katoria", "Rajoun", "Shambhuganj"],
    "Begusarai": ["Begusarai", "Bachhwara", "Barauni", "Balia", "Bhagwanpur", "Birpur", "Cheria Bariarpur", "Dandari", "Garhpura", "Khudabandpur", "Mansurchak", "Matihani", "Nawkothi", "Sahebpur Kamal", "Samho East", "Teghra"],
    "Bhagalpur": ["Bhagalpur", "Bihpur", "Gopalpur", "Jagdishpur", "Kahalgaon", "Kharik", "Khirsarai", "Naugachia", "Nathnagar", "Pirpainti", "Sabour", "Sanhaula", "Shahkund", "Sultanganj"],
    "Bhojpur": ["Arrah", "Agiaon", "Barhara", "Behea", "Charpokhari", "Garhani", "Jagdishpur", "Koilwar", "Piro", "Sandesh", "Sahar", "Shahpur", "Tarari", "Udwantnagar"],
    "Buxar": ["Buxar", "Brahmpur", "Chausa", "Chougain", "Dumraon", "Itarhi", "Kesath", "Nawanagar", "Rajpur", "Simri"],
    "Darbhanga": ["Darbhanga", "Alinagar", "Baheri", "Bahadurpur", "Benipur", "Biraul", "Ghanshyampur", "Gaura Bauram", "Hanuman Nagar", "Hayaghat", "Jale", "Keoti", "Kiratpur", "Kusheshwar Asthan", "Manigachhi", "Singhwara", "Tardih"],
    "East Champaran": ["Motihari", "Adapur", "Areraj", "Banjariya", "Chakia", "Dhaka", "Ghorasahan", "Harsidhi", "Kesaria", "Kotwa", "Mehsi", "Paharpur", "Pakridayal", "Patahi", "Phenhara", "Pipra", "Raxaul", "Sangrampur", "Sugauli", "Turkaulia"],
    "Gaya": ["Gaya", "Amas", "Atri", "Barachatti", "Belaganj", "Bodh Gaya", "Dobhi", "Fatehpur", "Gurua", "Imamganj", "Khizarsarai", "Konch", "Manpur", "Mohanpur", "Nawada", "Paraiya", "Sherghati", "Tankuppa", "Tekari", "Wazirganj"],
    "Gopalganj": ["Gopalganj", "Barauli", "Bhorey", "Bijaipur", "Hathua", "Kataiya", "Kuchaikote", "Manjha", "Phulwaria", "Sidhwalia", "Thawe", "Uchkagaon", "Vijayipur"],
    "Jamui": ["Jamui", "Barhat", "Chakai", "Gidhaur", "Jhajha", "Khaira", "Laxmipur", "Mallpur", "Sikandra", "Sono"],
    "Jehanabad": ["Jehanabad", "Ghoshi", "Hulasganj", "Kako", "Makhdumpur", "Modanganj", "Ratni Faridpur"],
    "Kaimur": ["Bhabua", "Adhaura", "Bhagwanpur", "Chainpur", "Chand", "Durgawati", "Kudra", "Mohania", "Nuaon", "Ramgarh", "Rampur"],
    "Katihar": ["Katihar", "Amdabad", "Azamnagar", "Balrampur", "Barari", "Barsoi", "Dandkhora", "Falka", "Kadwa", "Korha", "Manihari", "Mansahi", "Pranpur", "Sameli"],
    "Khagaria": ["Khagaria", "Alauli", "Chautham", "Gogri", "Mansi", "Parbalpur"],
    "Kishanganj": ["Kishanganj", "Bahadurganj", "Dighalbank", "Kochadhaman", "Pothia", "Terhagachh", "Thakurganj"],
    "Lakhisarai": ["Lakhisarai", "Barahiya", "Halsi", "Pipariya", "Ramgarh Chowk", "Surajgarha"],
    "Madhepura": ["Madhepura", "Alamnagar", "Bihariganj", "Chausa", "Gamharia", "Ghailarh", "Gwalpara", "Kumarkhand", "Murliganj", "Puraini", "Shankarpur", "Singheshwar"],
    "Madhubani": ["Madhubani", "Andharatharhi", "Babubarhi", "Basopatti", "Benipatti", "Bisfi", "Ghoghardiha", "Harlakhi", "Jaynagar", "Jhanjharpur", "Khajauli", "Ladania", "Laukaha", "Laukahi", "Madhepur", "Phulparas", "Rajnagar", "Rahika"],
    "Munger": ["Munger", "Asarganj", "Bariarpur", "Dharhara", "Haveli Kharagpur", "Jamalpur", "Kharagpur", "Sangrampur", "Tarapur", "Tetiya Bambar"],
    "Muzaffarpur": ["Muzaffarpur", "Aurai", "Bochaha", "Gaighat", "Kanti", "Katra", "Kurhani", "Maniyari", "Marwan", "Minapur", "Motipur", "Mushahari", "Paru", "Sahebganj", "Sakra", "Saraiya"],
    "Nalanda": ["Bihar Sharif", "Asthawan", "Ben", "Biharsharif", "Bind", "Chandi", "Ekangarsarai", "Giriyak", "Harnaut", "Hilsa", "Islampur", "Katyayan", "Noorsarai", "Rahui", "Rajgir", "Silao", "Sirmera", "Tharthari"],
    "Nawada": ["Nawada", "Akbarpur", "Govindpur", "Hisua", "Kashi Chak", "Kawakol", "Meskaur", "Nardiganj", "Narhat", "Pakribarwan", "Rajauli", "Roh", "Sirdala", "Warsaliganj"],
    "Patna": ["Patna", "Athmalgola", "Bakhtiyarpur", "Barh", "Belchi", "Bihta", "Bikram", "Danapur", "Dhanarua", "Dulhin Bazar", "Fatuha", "Ghoswari", "Khusrupur", "Maner", "Masaurhi", "Mokama", "Naubatpur", "Paliganj", "Pandarak", "Phulwari", "Punpun", "Sampatchak"],
    "Purnia": ["Purnia", "Amour", "Baisi", "Banmankhi", "Bhawanipur", "Byasi", "Dhamdaha", "Jalalgarh", "Kasba", "Krityanand Nagar", "Rupauli", "Srinagar"],
    "Rohtas": ["Sasaram", "Bikramganj", "Chenari", "Dawath", "Dehri", "Dinara", "Kargahar", "Naohatta", "Nasriganj", "Nokha", "Rajpur", "Rohtas", "Sanjhauli", "Sheosagar", "Shivsagar", "Suryapura", "Tilauthu"],
    "Saharsa": ["Saharsa", "Banma Itahri", "Kahara", "Mahishi", "Nauhatta", "Patarghat", "Sattar Katiya", "Simri Bakhtiyarpur", "Sonbarsha", "Salkhua"],
    "Samastipur": ["Samastipur", "Bibhutipur", "Bithan", "Dalsinghsarai", "Hasanpur", "Kalyanpur", "Mohiuddinagar", "Morwa", "Pusa", "Rosera", "Shivajinagar", "Singhia", "Tajpur", "Ujiarpur", "Vidyapati Nagar", "Warisnagar"],
    "Saran": ["Chhapra", "Amnour", "Baniapur", "Dariapur", "Dighwara", "Ekma", "Garkha", "Ishuapur", "Jalalpur", "Lahladpur", "Maker", "Manjhi", "Marhaura", "Mashrak", "Marhowrah", "Nagra", "Panapur", "Parsa", "Revelganj", "Sonepur", "Taraiya"],
    "Sheikhpura": ["Sheikhpura", "Ariyari", "Barbigha", "Chewara", "Ghatkusumbha", "Shekhopur Sarai"],
    "Sheohar": ["Sheohar", "Piprahi", "Purnahiya", "Tariyani"],
    "Sitamarhi": ["Sitamarhi", "Bajpatti", "Bathnaha", "Belsand", "Bokhra", "Choraut", "Dumra", "Majorganj", "Nanpur", "Parsauni", "Parihar", "Pupri", "Riga", "Runnisaidpur", "Sonbarsa", "Suppi"],
    "Siwan": ["Siwan", "Andar", "Barharia", "Basantpur", "Bhagwanpur Hat", "Darauli", "Daraundha", "Goriakothi", "Hussainganj", "Lakri Nabiganj", "Maharajganj", "Mairwa", "Nautan", "Pachrukhi", "Raghunathpur", "Siswan", "Ziradei"],
    "Supaul": ["Supaul", "Basantpur", "Birpur", "Chhatapur", "Kishanpur", "Nirmali", "Pipra", "Pratapganj", "Raghopur", "Saraigarh Bhaptiyahi", "Triveniganj"],
    "Vaishali": ["Hajipur", "Bhagwanpur", "Bidupur", "Desri", "Goraul", "Jandaha", "Lalganj", "Mahua", "Mahnar", "Patepur", "Patti", "Raja Pakar", "Raghopur", "Sahdei Buzurg", "Vaishali"],
    "West Champaran": ["Bettiah", "Bagaha", "Chanpatia", "Gaunaha", "Jogapatti", "Lauriya", "Mainatand", "Nautan", "Narkatiaganj", "Piprasi", "Ramnagar", "Shikarpur", "Sikta", "Thakrahan"]
  },

  "Chandigarh": {
    "Chandigarh": ["Chandigarh", "Manimajra", "Panchkula", "Mohali", "Sector 17", "Sector 22", "Sector 35"]
  },

  "Chhattisgarh": {
    "Balod": ["Balod", "Dondi", "Dondi Lohara", "Gunderdehi"],
    "Baloda Bazar": ["Baloda Bazar", "Bhatapara", "Bilaigarh", "Kasdol", "Palari", "Simga"],
    "Balrampur": ["Balrampur", "Rajpur", "Ramanujganj", "Shankargarh", "Wadrafnagar"],
    "Bastar": ["Jagdalpur", "Bakawand", "Bastar", "Darbha", "Lohandiguda", "Tokapal"],
    "Bemetara": ["Bemetara", "Berla", "Nawagarh", "Saja", "Thakurtola"],
    "Bijapur": ["Bijapur", "Bhairamgarh", "Bhopalpatnam", "Usur"],
    "Bilaspur": ["Bilaspur", "Bilha", "Kota", "Lormi", "Masturi", "Mungeli", "Pendra", "Takhatpur"],
    "Dantewada": ["Dantewada", "Bacheli", "Barsur", "Geedam", "Katekalyan", "Kuakonda"],
    "Dhamtari": ["Dhamtari", "Kurud", "Magarlod", "Nagri"],
    "Durg": ["Durg", "Ahiwara", "Bhilai", "Dhamdha", "Patan"],
    "Gariaband": ["Gariaband", "Chhura", "Deobhog", "Fingeshwar", "Mainpur"],
    "Gaurela-Pendra-Marwahi": ["Gaurela", "Pendra", "Marwahi"],
    "Janjgir-Champa": ["Janjgir", "Akaltara", "Baloda", "Champa", "Jaijaipur", "Malkharoda", "Naila", "Pamgarh", "Sakti"],
    "Jashpur": ["Jashpur", "Bagicha", "Duldula", "Farsabahar", "Kunkuri", "Manora", "Pathalgaon"],
    "Kabirdham": ["Kawardha", "Bodla", "Kunda", "Pandariya", "Sahaspur Lohara"],
    "Kanker": ["Kanker", "Antagarh", "Bhanupratappur", "Charama", "Durgukondal", "Koylibeda", "Narharpur", "Pakhanjur"],
    "Kondagaon": ["Kondagaon", "Baderajpur", "Farasgaon", "Keshkal", "Makdi"],
    "Korba": ["Korba", "Kartala", "Katghora", "Pali", "Podi Uproda"],
    "Koriya": ["Baikunthpur", "Bharatpur", "Bhaiyathan", "Janakpur", "Manendragarh", "Sonhat"],
    "Mahasamund": ["Mahasamund", "Bagbahra", "Basna", "Pithora", "Saraipali"],
    "Mohla-Manpur": ["Mohla", "Manpur"],
    "Mungeli": ["Mungeli", "Lormi", "Patharia"],
    "Narayanpur": ["Narayanpur", "Orchha"],
    "Raigarh": ["Raigarh", "Baramkela", "Dharamjaigarh", "Gharghoda", "Kharsia", "Lailunga", "Pussore", "Sarangarh", "Tamnar"],
    "Raipur": ["Raipur", "Abhanpur", "Arang", "Dharsiwa", "Tilda"],
    "Rajnandgaon": ["Rajnandgaon", "Chhuriya", "Chhuikhadan", "Dongargaon", "Khairagarh", "Mohla", "Manpur"],
    "Sakti": ["Sakti", "Jaijaipur", "Janjgir"],
    "Sarangarh-Bilaigarh": ["Sarangarh", "Bilaigarh"],
    "Sukma": ["Sukma", "Chhindgarh", "Konta"],
    "Surajpur": ["Surajpur", "Bhaiyathan", "Premnagar", "Ramanujnagar"],
    "Surguja": ["Ambikapur", "Batauli", "Lakhanpur", "Lundra", "Odgi", "Pratappur", "Rajpur", "Sitapur", "Udaipur"]
  },
  "Dadra and Nagar Haveli and Daman and Diu": {
    "Dadra and Nagar Haveli": ["Silvassa", "Amli", "Dadra", "Khanvel", "Naroli", "Rakholi"],
    "Daman": ["Daman", "Moti Daman", "Nani Daman"],
    "Diu": ["Diu", "Bucharwada", "Ghoghla", "Sutrapada"]
  },

  "Delhi": {
    "Central": ["Civil Lines", "Karol Bagh", "Kotwali"],
    "East": ["Gandhi Nagar", "Mayur Vihar", "Preet Vihar"],
    "New Delhi": ["Chanakyapuri", "Delhi Cantonment", "Vasant Vihar"],
    "North": ["Alipur", "Model Town", "Narela"],
    "North East": ["Karawal Nagar", "Seelampur", "Yamuna Vihar"],
    "North West": ["Kanjhawala", "Rohini", "Saraswati Vihar"],
    "Shahdara": ["Seema Puri", "Shahdara", "Vivek Vihar"],
    "South": ["Hauz Khas", "Mehrauli", "Saket"],
    "South East": ["Defence Colony", "Kalkaji", "Sarita Vihar"],
    "South West": ["Dwarka", "Kapeshera", "Najafgarh"],
    "West": ["Patel Nagar", "Punjabi Bagh", "Rajouri Garden"]
  },
  "Goa": {
    "North Goa": ["Panaji", "Bardez", "Bicholim", "Mapusa", "Pernem", "Ponda", "Sattari", "Tiswadi"],
    "South Goa": ["Margao", "Canacona", "Dharbandora", "Mormugao", "Quepem", "Salcete", "Sanguem"]
  },

  "Gujarat": {
    "Ahmedabad": ["Ahmedabad City", "Bavla", "Daskroi", "Detroj-Rampura", "Dhandhuka", "Dholka", "Mandal", "Sanand", "Viramgam"],
    "Amreli": ["Amreli", "Bagasara", "Babra", "Dhari", "Jafrabad", "Khambha", "Kunkavav Vadia", "Lathi", "Lilia", "Rajula", "Savarkundla"],
    "Anand": ["Anand", "Anklav", "Borsad", "Khambhat", "Petlad", "Sojitra", "Tarapur", "Umreth"],
    "Aravalli": ["Modasa", "Bayad", "Bhiloda", "Dhansura", "Malpur", "Meghraj"],
    "Banaskantha": ["Palanpur", "Amirgadh", "Bhabhar", "Danta", "Dantiwada", "Deesa", "Dhanera", "Kankrej", "Lakhani", "Radhanpur", "Suigam", "Tharad", "Vadgam", "Vav"],
    "Bharuch": ["Bharuch", "Amod", "Ankleshwar", "Hansot", "Jambusar", "Jhagadia", "Netrang", "Vagra", "Valia"],
    "Bhavnagar": ["Bhavnagar", "Gariadhar", "Ghogha", "Jesar", "Mahuva", "Palitana", "Shihor", "Sihor", "Talaja", "Umrala", "Vallabhipur"],
    "Botad": ["Botad", "Barwala", "Gadhada", "Ranpur"],
    "Chhota Udaipur": ["Chhota Udaipur", "Bodeli", "Jetpur Pavi", "Kavant", "Nasvadi", "Pavi Jetpur", "Sankheda"],
    "Dahod": ["Dahod", "Devgadh Baria", "Dhanpur", "Fatepura", "Garbada", "Jhalod", "Limkheda", "Zalod"],
    "Dang": ["Ahwa", "Subir", "Waghai"],
    "Devbhoomi Dwarka": ["Khambhalia", "Bhanvad", "Dwarka", "Kalyanpur"],
    "Gandhinagar": ["Gandhinagar", "Dahegam", "Dehgam", "Kalol", "Mansa"],
    "Gir Somnath": ["Veraval", "Kodinar", "Sutrapada", "Talala", "Una"],
    "Jamnagar": ["Jamnagar", "Dhrol", "Jodiya", "Jodia", "Kalavad", "Lalpur"],
    "Junagadh": ["Junagadh", "Bhesan", "Keshod", "Mangrol", "Manavadar", "Mendarda", "Vanthali", "Visavadar"],
    "Kheda": ["Nadiad", "Balasinor", "Kapadvanj", "Kathlal", "Kheda", "Matar", "Mehmedabad", "Thasra", "Vaso"],
    "Kutch": ["Bhuj", "Abdasa", "Anjar", "Bhachau", "Gandhidham", "Lakhpat", "Mandvi", "Mundra", "Nakhatrana", "Rapar"],
    "Mahisagar": ["Lunawada", "Balasinor", "Kadana", "Khanpur", "Santrampur", "Virpur"],
    "Mehsana": ["Mehsana", "Becharaji", "Kadi", "Kheralu", "Satlasana", "Sidhpur", "Unjha", "Vadnagar", "Vijapur", "Visnagar"],
    "Morbi": ["Morbi", "Halvad", "Maliya Miyana", "Tankara", "Wankaner"],
    "Narmada": ["Rajpipla", "Dediapada", "Garudeshwar", "Nandod", "Sagbara", "Tilakwada"],
    "Navsari": ["Navsari", "Chikhli", "Gandevi", "Jalalpore", "Khergam", "Vansda"],
    "Panchmahal": ["Godhra", "Ghoghamba", "Halol", "Jambughoda", "Kalol", "Lunawada", "Morva Hadaf", "Shahera"],
    "Patan": ["Patan", "Chanasma", "Harij", "Radhanpur", "Sami", "Santalpur", "Saraswati", "Sidhpur"],
    "Porbandar": ["Porbandar", "Kutiyana", "Ranavav"],
    "Rajkot": ["Rajkot", "Dhoraji", "Gondal", "Jasdan", "Jetpur", "Kotda Sangani", "Lodhika", "Paddhari", "Upleta", "Vinchhiya", "Wankaner"],
    "Sabarkantha": ["Himmatnagar", "Bayad", "Idar", "Khedbrahma", "Meghraj", "Prantij", "Talod", "Vadali", "Vijaynagar"],
    "Surat": ["Surat", "Bardoli", "Kamrej", "Mahuva", "Mandvi", "Mangrol", "Olpad", "Palsana", "Umarpada"],
    "Surendranagar": ["Surendranagar", "Chuda", "Chotila", "Dhrangadhra", "Halvad", "Lakhtar", "Limbdi", "Muli", "Sayla", "Thangadh", "Wadhwan"],
    "Tapi": ["Vyara", "Dolvan", "Kukarmunda", "Nizar", "Songadh", "Uchchhal", "Valod"],
    "Vadodara": ["Vadodara", "Dabhoi", "Desar", "Karjan", "Padra", "Savli", "Shinor", "Vaghodia"],
    "Valsad": ["Valsad", "Dharampur", "Kaprada", "Pardi", "Umbergaon", "Vapi"]
  },

  "Haryana": {
    "Ambala": ["Ambala", "Ambala Cantonment", "Barara", "Mullana", "Naraingarh", "Saha", "Shahzadpur"],
    "Bhiwani": ["Bhiwani", "Bahal", "Bawani Khera", "Behal", "Kairu", "Loharu", "Siwani", "Tosham"],
    "Charkhi Dadri": ["Charkhi Dadri", "Badhra", "Baund Kalan"],
    "Faridabad": ["Faridabad", "Ballabhgarh", "Tigaon"],
    "Fatehabad": ["Fatehabad", "Bhattu Kalan", "Jakhal", "Ratia", "Tohana"],
    "Gurugram": ["Gurugram", "Farukhnagar", "Manesar", "Pataudi", "Sohna"],
    "Hisar": ["Hisar", "Adampur", "Agroha", "Barwala", "Hansi", "Narnaund", "Uklana"],
    "Jhajjar": ["Jhajjar", "Bahadurgarh", "Beri", "Machhrauli", "Matanhail", "Salhawas"],
    "Jind": ["Jind", "Julana", "Narwana", "Pillukhera", "Safidon", "Uchana"],
    "Kaithal": ["Kaithal", "Guhla", "Kalayat", "Pundri", "Rajound", "Siwan"],
    "Karnal": ["Karnal", "Assandh", "Gharaunda", "Indri", "Nilokheri"],
    "Kurukshetra": ["Kurukshetra", "Babain", "Ladwa", "Pehowa", "Shahabad", "Thanesar"],
    "Mahendragarh": ["Narnaul", "Ateli", "Kanina", "Mahendragarh", "Nangal Chaudhry"],
    "Mewat": ["Nuh", "Ferozpur Jhirka", "Nagina", "Punhana", "Tauru"],
    "Palwal": ["Palwal", "Hathin", "Hodal"],
    "Panchkula": ["Panchkula", "Barwala", "Morni", "Raipur Rani"],
    "Panipat": ["Panipat", "Bapoli", "Israna", "Madlauda", "Samalkha"],
    "Rewari": ["Rewari", "Bawal", "Dharuhera", "Jatusana", "Khol"],
    "Rohtak": ["Rohtak", "Asthal Bohar", "Kalanaur", "Lakhan Majra", "Maham", "Sampla"],
    "Sirsa": ["Sirsa", "Dabwali", "Ellenabad", "Nathusari Chopta", "Odhan", "Rania"],
    "Sonipat": ["Sonipat", "Ganaur", "Gohana", "Kharkhoda", "Mundlana", "Rai"],
    "Yamunanagar": ["Yamunanagar", "Bilaspur", "Chhachhrauli", "Jagadhri", "Mustafabad", "Radaur", "Sadhaura"]
  },

  "Himachal Pradesh": {
    "Bilaspur": [
      "Bharari",
      "Bilaspur Sadar",
      "Ghumarwin",
      "Jhanduta",
      "Kalol",
      "Naina Devi",
      "Namhol"
    ],
    "Chamba": [
      "Bhalai",
      "Bharmour",
      "Bhattiyat",
      "Chamba",
      "Churah",
      "Dalhousie",
      "Dharwala",
      "Holi",
      "Kakira",
      "Pangi",
      "Pukhri",
      "Saho",
      "Saluni",
      "Sihunta",
      "Telka"
    ],
    "Hamirpur": [
      "Barsar",
      "Bhoranj",
      "Bhota",
      "Dhatwal",
      "Galore",
      "Hamirpur",
      "Jahu",
      "Kangoo",
      "Lambloo",
      "Nadaun",
      "Tauni Devi Bamson",
      "Tira Sujanpur"
    ],
    "Kangra": [
      "Alampur",
      "Baijnath",
      "Baroh",
      "Bharoli",
      "Bhawarna",
      "Chadiyar",
      "Dadasiba",
      "Dareeni",
      "Dehra Gopipur",
      "Dharmsala",
      "Dhira",
      "Fatehpur",
      "Gangath",
      "Harchakian",
      "Haripur",
      "Indora",
      "Jaisinghpur",
      "Jaswan",
      "Jawalamukhi",
      "Jawali",
      "Kangra",
      "Khundian",
      "Kotla",
      "Lagru",
      "Majheen",
      "Multhan",
      "Nagrota Bagwan",
      "Nagrota Surian",
      "Nurpur",
      "Palampur",
      "Panchrukhi",
      "Pragpur",
      "Raja Ka Talab",
      "Rakkar",
      "Rey",
      "Sadwan",
      "Shahpur",
      "Sulah",
      "Thakurdwara",
      "Thural"
    ],
    "Kinnaur": [
      "Hangrang",
      "Kalpa",
      "Morang",
      "Nichar",
      "Poo",
      "Sangla",
      "Tapri"
    ],
    "Kullu": [
      "Ani",
      "Banjar",
      "Bhuntar",
      "Jari",
      "Kullu",
      "Manali",
      "Nirmand",
      "Nither",
      "Sainj"
    ],
    "Lahaul and Spiti": [
      "Lahul",
      "Spiti",
      "Udaipur"
    ],
    "Mandi": [
      "Aut",
      "Bagachnogi",
      "Bagshad",
      "Baldwara",
      "Balh",
      "Bali Chowki",
      "Bhadrota",
      "Chachyot",
      "Chhatri",
      "Dehar",
      "Dhalwan",
      "Dharmpur",
      "Jogindarnagar",
      "Karsog",
      "Katoula",
      "Kotli",
      "Lad Bharol",
      "Makridi",
      "Mandap",
      "Mandi",
      "Nihri",
      "Padhar",
      "Pangna",
      "Rewalsar",
      "Sandhol",
      "Sarkaghat",
      "Sundarnagar",
      "Thachi",
      "Thunag",
      "Tihra",
      "Tikken"
    ],
    "Shimla": [
      "Chaupal",
      "Chirgaon",
      "Deha",
      "Dhami",
      "Dodra Kwar",
      "Jalog",
      "Jangla",
      "Jubbal",
      "Junga",
      "Kalbog",
      "Kotgarh",
      "Kotkhai",
      "Kumarsain",
      "Kupvi",
      "Nankhari",
      "Nerwa",
      "Rampur",
      "Rohru",
      "Sarahan",
      "Sarawati Nagar",
      "Shimla (Rural)",
      "Shimla (Urban)",
      "Sunni",
      "Taklech",
      "Theog",
      "Tikar"
    ],
    "Sirmaur": [
      "Dadahu",
      "Haripurdhar",
      "Kamrau",
      "Majra",
      "Nahan",
      "Narag",
      "Nohra",
      "Pachhad",
      "Pajhota",
      "Paonta Sahib",
      "Rajgarh",
      "Renuka",
      "Ronhat",
      "Shillai"
    ],
    "Solan": [
      "Arki",
      "Baddi",
      "Darlaghat",
      "Kandaghat",
      "Kasauli",
      "Krishangarh",
      "Kunihar",
      "Loharghat",
      "Mamlig",
      "Nalagarh",
      "Panjehra",
      "Parwanoo",
      "Ramshahr",
      "Solan"
    ],
    "Una": [
      "Amb",
      "Bangana",
      "Bharwain",
      "Birhu Kalan",
      "Dulahar",
      "Gagret",
      "Ghanari",
      "Haroli",
      "Ispur",
      "Jol",
      "Mehatpur",
      "Una"
    ]
  },

  "Jammu and Kashmir": {
    "Anantnag": ["Anantnag", "Bijbehara", "Breng", "Dooru", "Kokernag", "Pahalgam", "Qazigund", "Shangus", "Srigufwara"],
    "Bandipora": ["Bandipora", "Gurez", "Hajin", "Sumbal"],
    "Baramulla": ["Baramulla", "Boniyar", "Kreeri", "Kunzer", "Pattan", "Rafiabad", "Rohama", "Sopore", "Uri", "Wagoora"],
    "Budgam": ["Budgam", "Beerwah", "Chadoora", "Charar-i-Sharief", "Khansahib", "Khag", "Narbal", "Soibugh"],
    "Doda": ["Doda", "Bhaderwah", "Bhagwah", "Chiralla", "Gandoh", "Kahara", "Thathri"],
    "Ganderbal": ["Ganderbal", "Kangan", "Lar", "Tullamulla", "Wakura"],
    "Jammu": ["Jammu", "Akhnoor", "Bishnah", "Khour", "Marh", "Nagrota", "Ranbir Singh Pura", "Suchetgarh"],
    "Kathua": ["Kathua", "Basholi", "Billawar", "Bani", "Dinga Amb", "Hiranagar", "Mahanpur", "Nagri", "Ramkot"],
    "Kishtwar": ["Kishtwar", "Chatroo", "Drabshalla", "Marwah", "Mughal Maidan", "Nagseni", "Padder"],
    "Kulgam": ["Kulgam", "Devsar", "D.H.Pora", "Frisal", "Pahloo", "Qaimoh", "Yaripora"],
    "Kupwara": ["Kupwara", "Handwara", "Karnah", "Keran", "Langate", "Lolab", "Machil", "Sogam", "Trehgam"],
    "Poonch": ["Poonch", "Haveli", "Mankote", "Mendhar", "Mender", "Surankote"],
    "Pulwama": ["Pulwama", "Aripal", "Awantipora", "Kakapora", "Pampore", "Rajpora", "Tral"],
    "Rajouri": ["Rajouri", "Budhal", "Darhal", "Kalakote", "Khawas", "Kotranka", "Manjakote", "Nowshera", "Sunderbani", "Thanamandi"],
    "Ramban": ["Ramban", "Banihal", "Batote", "Gool", "Ramsu"],
    "Reasi": ["Reasi", "Arnas", "Chassana", "Gulabgarh", "Katra", "Mahore", "Pouni", "Shri Mata Vaishno Devi"],
    "Samba": ["Samba", "Bari Brahmana", "Ghagwal", "Nud", "Ramgarh", "Vijaypur"],
    "Shopian": ["Shopian", "Barbough", "Chitragam", "Hermain", "Keegam", "Kellar", "Zainpora"],
    "Srinagar": ["Srinagar", "Eidgah", "Hazratbal", "Khanyar", "Shalteng"],
    "Udhampur": ["Udhampur", "Basantgarh", "Chenani", "Dudu Basantgarh", "Latti", "Majalta", "Moungri", "Ramnagar"]
  },

  "Jharkhand": {
    "Bokaro": ["Bokaro Steel City", "Bermo", "Chas", "Chandankiyari", "Gomia", "Jaridih", "Nawadih", "Peterbar"],
    "Chatra": ["Chatra", "Hunterganj", "Itkhori", "Kunda", "Lawalong", "Pathalgada", "Pratappur", "Simaria"],
    "Deoghar": ["Deoghar", "Madhupur", "Mohanpur", "Palajori", "Sarwan", "Sarth"],
    "Dhanbad": ["Dhanbad", "Baghmara", "Baliapur", "Jharia", "Nirsa", "Sindri", "Topchanchi", "Tundi"],
    "Dumka": ["Dumka", "Gopikandar", "Jama", "Jarmundi", "Kathikund", "Masalia", "Ramgarh", "Raneshwar", "Shikaripara"],
    "East Singhbhum": ["Jamshedpur", "Baharagora", "Boram", "Dhalbhum", "Ghatsila", "Musabani", "Patamda", "Potka"],
    "Garhwa": ["Garhwa", "Bhandaria", "Bhawnathpur", "Dhurki", "Ketar", "Manjhiaon", "Meral", "Nagar Untari", "Ranka"],
    "Giridih": ["Giridih", "Bagodar", "Bengabad", "Birni", "Deori", "Dhanwar", "Dumri", "Gandey", "Gawan", "Jamua", "Pirtand", "Surya"],
    "Godda": ["Godda", "Boarijor", "Mahagama", "Pathargama", "Poraiyahat", "Sunderpahari"],
    "Gumla": ["Gumla", "Bishunpur", "Basia", "Chainpur", "Dumri", "Ghaghra", "Kamdara", "Palkot", "Raidih", "Sisai"],
    "Hazaribagh": ["Hazaribagh", "Barhi", "Barkagaon", "Bishungarh", "Chouparan", "Churchu", "Daru", "Ichak", "Katkamsandi", "Mandu", "Padma"],
    "Jamtara": ["Jamtara", "Fatehpur", "Kundhit", "Nala", "Narayanpur"],
    "Khunti": ["Khunti", "Arki", "Karra", "Murhu", "Rania", "Torpa"],
    "Koderma": ["Koderma", "Chandwara", "Domchanch", "Jainagar", "Markacho", "Satgawan"],
    "Latehar": ["Latehar", "Balumath", "Barwadih", "Chandwa", "Garu", "Herhal", "Manika", "Rahe"],
    "Lohardaga": ["Lohardaga", "Bhandra", "Kisko", "Kuru", "Senha"],
    "Pakur": ["Pakur", "Amrapara", "Hiranpur", "Littipara", "Maheshpur", "Pakuria"],
    "Palamu": ["Daltonganj", "Bishrampur", "Chainpur", "Chhatarpur", "Hariharganj", "Hussainabad", "Leslieganj", "Manatu", "Medininagar", "Pandu", "Patan", "Satbarwa", "Tarhasi"],
    "Ramgarh": ["Ramgarh", "Chitarpur", "Dulmi", "Gola", "Mandu", "Patratu"],
    "Ranchi": ["Ranchi", "Angara", "Bero", "Bundu", "Burmu", "Chanho", "Kanke", "Khijri", "Lapung", "Mandar", "Nagri", "Namkum", "Ormanjhi", "Ratu", "Silli", "Sonahatu", "Tamar"],
    "Sahebganj": ["Sahebganj", "Barharwa", "Barhait", "Borio", "Mandro", "Pathna", "Rajmahal", "Taljhari", "Udhwa"],
    "Seraikela Kharsawan": ["Seraikela", "Chandil", "Gamharia", "Ichagarh", "Kharsawan", "Kuchai", "Nimdih", "Rajnagar"],
    "Simdega": ["Simdega", "Bano", "Bolba", "Jaldega", "Kolebira", "Kurdeg", "Pakartanr", "Thethaitangar"],
    "West Singhbhum": ["Chaibasa", "Chakradharpur", "Goilkera", "Gudri", "Jagannathpur", "Jhinkpani", "Khuntpani", "Kumardungi", "Manjhari", "Manoharpur", "Noamundi", "Sonua", "Tonto"]
  },

  "Karnataka": {
    "Bagalkot": ["Bagalkot", "Badami", "Bilgi", "Hungund", "Ilkal", "Jamkhandi", "Mudhol"],
    "Ballari": ["Ballari", "Hadagali", "Hagaribommanahalli", "Hospet", "Kudligi", "Sandur", "Siruguppa"],
    "Belagavi": ["Belagavi", "Athani", "Bailhongal", "Chikkodi", "Gokak", "Hukkeri", "Khanapur", "Raibag", "Ramdurg", "Savadatti"],
    "Bengaluru Rural": ["Devanahalli", "Doddaballapur", "Hosakote", "Nelamangala"],
    "Bengaluru Urban": ["Bengaluru", "Anekal", "Bengaluru East", "Bengaluru North", "Bengaluru South", "Bengaluru West", "Yelahanka"],
    "Bidar": ["Bidar", "Aurad", "Basavakalyan", "Bhalki", "Humnabad"],
    "Chamarajanagar": ["Chamarajanagar", "Gundlupet", "Hanur", "Kollegal", "Yelandur"],
    "Chikkaballapur": ["Chikkaballapur", "Bagepalli", "Chintamani", "Gauribidanur", "Gudibande", "Sidlaghatta"],
    "Chikkamagaluru": ["Chikkamagaluru", "Kadur", "Koppa", "Mudigere", "N.R.Pura", "Sringeri", "Tarikere"],
    "Chitradurga": ["Chitradurga", "Challakere", "Hiriyur", "Holalkere", "Hosadurga", "Molakalmuru"],
    "Dakshina Kannada": ["Mangaluru", "Bantval", "Belthangady", "Moodabidri", "Puttur", "Sullia", "Ullal"],
    "Davanagere": ["Davanagere", "Channagiri", "Harihar", "Harpanahalli", "Honnali", "Jagalur"],
    "Dharwad": ["Dharwad", "Hubli", "Kalghatgi", "Kundgol", "Navalgund"],
    "Gadag": ["Gadag", "Mundargi", "Nargund", "Ron", "Shirahatti"],
    "Hassan": ["Hassan", "Alur", "Arakalagudu", "Arkalgud", "Belur", "Channarayapatna", "Holenarasipur", "Sakleshpur"],
    "Haveri": ["Haveri", "Byadagi", "Hanagal", "Hirekerur", "Ranebennur", "Savanur", "Shiggaon"],
    "Kalaburagi": ["Kalaburagi", "Afzalpur", "Aland", "Chincholi", "Chittapur", "Jevargi", "Sedam", "Yadgir"],
    "Kodagu": ["Madikeri", "Somwarpet", "Virajpet"],
    "Kolar": ["Kolar", "Bangarpet", "KGF", "Malur", "Mulbagal", "Srinivaspur"],
    "Koppal": ["Koppal", "Gangavathi", "Kushtagi", "Yelburga"],
    "Mandya": ["Mandya", "Kirugavalu", "Krishnarajapete", "Maddur", "Malavalli", "Nagamangala", "Pandavapura", "Srirangapatna"],
    "Mysuru": ["Mysuru", "H.D.Kote", "Hunsur", "K.R.Nagar", "Nanjangud", "Periyapatna", "T.Narasipur"],
    "Raichur": ["Raichur", "Devadurga", "Lingsugur", "Manvi", "Mudgal", "Sindhanur"],
    "Ramanagara": ["Ramanagara", "Channapatna", "Kanakapura", "Magadi"],
    "Shivamogga": ["Shivamogga", "Bhadravati", "Hosanagara", "Sagara", "Shikaripura", "Soraba", "Thirthahalli"],
    "Tumakuru": ["Tumakuru", "Chiknayakanhalli", "Gubbi", "Koratagere", "Kunigal", "Madhugiri", "Pavagada", "Sira", "Tiptur", "Turuvekere"],
    "Udupi": ["Udupi", "Brahmavar", "Kundapur", "Karkala"],
    "Uttara Kannada": ["Karwar", "Ankola", "Bhatkal", "Dandeli", "Haliyal", "Honavar", "Joida", "Kumta", "Mundgod", "Siddapur", "Sirsi", "Supa", "Yellapur"],
    "Vijayapura": ["Vijayapura", "Basavana Bagewadi", "Bilagi", "Indi", "Muddebihal", "Sindagi"],
    "Yadgir": ["Yadgir", "Gurmitkal", "Hunasagi", "Shahapur", "Shorapur", "Wadagera"]
  },

  "Kerala": {
    "Alappuzha": ["Alappuzha", "Ambalappuzha", "Aroor", "Chengannur", "Cherthala", "Harippad", "Karthikappally", "Kuttanad", "Mavelikkara", "Mavelikara"],
    "Ernakulam": ["Ernakulam", "Aluva", "Angamaly", "Kanayannur", "Kochi", "Kothamangalam", "Kunnathunad", "Muvattupuzha", "North Paravur", "Paravur", "Perumbavoor"],
    "Idukki": ["Idukki", "Devikulam", "Peerumade", "Thodupuzha", "Udumbanchola"],
    "Kannur": ["Kannur", "Iritty", "Koothuparamba", "Payyannur", "Taliparamba", "Thalassery"],
    "Kasaragod": ["Kasaragod", "Hosdurg", "Manjeshwar", "Vellarikundu"],
    "Kollam": ["Kollam", "Chathannoor", "Chadayamangalam", "Karunagappally", "Kottarakkara", "Kunnathur", "Pathanapuram", "Punalur"],
    "Kottayam": ["Kottayam", "Changanassery", "Ettumanoor", "Kanjirappally", "Meenachil", "Pala", "Vaikom"],
    "Kozhikode": ["Kozhikode", "Koyilandy", "Mukkam", "Perambra", "Quilandy", "Thamarassery", "Vadakara"],
    "Malappuram": ["Malappuram", "Eranad", "Kondotty", "Manjeri", "Nilambur", "Perinthalmanna", "Ponnani", "Tirur", "Tiruvali"],
    "Palakkad": ["Palakkad", "Alathur", "Attappady", "Chittur", "Mannarkkad", "Ottapalam", "Pattambi", "Shoranur", "Thrithala"],
    "Pathanamthitta": ["Pathanamthitta", "Adoor", "Kozhencherry", "Mallappally", "Ranni", "Thiruvalla", "Tiruvalla"],
    "Thiruvananthapuram": ["Thiruvananthapuram", "Chirayinkeezhu", "Kazhakootam", "Kattakada", "Nedumangad", "Neyyattinkara", "Varkala"],
    "Thrissur": ["Thrissur", "Chalakudy", "Chavakkad", "Kodungallur", "Kunnamkulam", "Mukundapuram", "Talappilly"],
    "Wayanad": ["Kalpetta", "Mananthavady", "Sulthan Bathery", "Vythiri"]
  },

  "Ladakh": {
    "Kargil": ["Kargil", "Drass", "Sankoo", "Shakar Chiktan", "Zanskar"],
    "Leh": ["Leh", "Diskit", "Khaltsi", "Nubra", "Nyoma", "Pangong", "Sham"]
  },

  "Lakshadweep": {
    "Lakshadweep": ["Kavaratti", "Agatti", "Amini", "Andrott", "Bitra", "Chetlat", "Kadmat", "Kalpeni", "Kiltan", "Minicoy"]
  },
  "Madhya Pradesh": {
    "Agar Malwa": ["Agar", "Barod", "Nalkheda", "Susner"],
    "Alirajpur": ["Alirajpur", "Bhabra", "Jobat", "Katthiwada", "Sondwa", "Udaigarh"],
    "Anuppur": ["Anuppur", "Jaithari", "Kotma", "Pushparajgarh"],
    "Ashoknagar": ["Ashoknagar", "Chanderi", "Isagarh", "Mungaoli"],
    "Balaghat": ["Balaghat", "Baihar", "Birsa", "Katangi", "Kirnapur", "Lanji", "Paraswada", "Waraseoni"],
    "Barwani": ["Barwani", "Anjad", "Badwani", "Niwali", "Pansemal", "Rajpur", "Sendhwa", "Thikri"],
    "Betul": ["Betul", "Amla", "Athner", "Bhainsdehi", "Chicholi", "Ghoradongri", "Multai", "Prabhatpattan", "Shahpur"],
    "Bhind": ["Bhind", "Ater", "Gohad", "Lahar", "Mehgaon", "Mihona", "Raun"],
    "Bhopal": ["Bhopal", "Berasia", "Phanda"],
    "Burhanpur": ["Burhanpur", "Khaknar", "Nepanagar"],
    "Chhatarpur": ["Chhatarpur", "Bada Malhera", "Bijawar", "Gaurihar", "Harpalpur", "Laundi", "Nowgong", "Rajnagar"],
    "Chhindwara": ["Chhindwara", "Amarwara", "Bichhua", "Chaurai", "Harrai", "Jamai", "Junnardeo", "Mohkhed", "Pandhurna", "Parasia", "Sausar", "Tamia"],
    "Damoh": ["Damoh", "Batiyagarh", "Hatta", "Jabera", "Patera", "Patharia", "Tendukheda"],
    "Datia": ["Datia", "Bhander", "Indergarh", "Seondha"],
    "Dewas": ["Dewas", "Bagli", "Kannod", "Khategaon", "Sonkatch", "Tonk Khurd"],
    "Dhar": ["Dhar", "Badnawar", "Dharampuri", "Gandhwani", "Kukshi", "Manawar", "Nalchha", "Sardarpur", "Tirla"],
    "Dindori": ["Dindori", "Amarpur", "Bajag", "Karanjia", "Mehandwani", "Samnapur", "Shahpura"],
    "Guna": ["Guna", "Aron", "Bamori", "Chachoda", "Kumbhraj", "Myana", "Raghogarh"],
    "Gwalior": ["Gwalior", "Bhitarwar", "Dabra", "Morar"],
    "Harda": ["Harda", "Khirkiya", "Timarni"],
    "Hoshangabad": ["Hoshangabad", "Babai", "Bankhedi", "Itarsi", "Kesla", "Pipariya", "Seoni Malwa", "Sohagpur"],
    "Indore": ["Indore", "Depalpur", "Hatod", "Mhow", "Sanwer"],
    "Jabalpur": ["Jabalpur", "Bargi", "Katangi", "Kundam", "Majholi", "Patan", "Shahpura", "Sihora"],
    "Jhabua": ["Jhabua", "Meghnagar", "Petlawad", "Rama", "Ranapur", "Thandla"],
    "Katni": ["Katni", "Bahoriband", "Barhi", "Dhimarkheda", "Rithi", "Vijayraghavgarh"],
    "Khandwa": ["Khandwa", "Harsud", "Khalwa", "Mandhata", "Pandhana", "Punasa"],
    "Khargone": ["Khargone", "Barwaha", "Bhikangaon", "Gogawan", "Kasrawad", "Maheshwar", "Segaon", "Ziranya"],
    "Mandla": ["Mandla", "Bichhia", "Ghughari", "Mawai", "Naiwara", "Nainpur", "Niwas"],
    "Mandsaur": ["Mandsaur", "Daloda", "Garoth", "Malhargarh", "Sitamau", "Suwasra"],
    "Morena": ["Morena", "Ambah", "Joura", "Kailaras", "Porsa", "Sabalgarh"],
    "Narsinghpur": ["Narsinghpur", "Chichli", "Gadarwara", "Gotegaon", "Kareli", "Saikheda", "Tendukheda"],
    "Neemuch": ["Neemuch", "Jawad", "Manasa"],
    "Niwari": ["Niwari", "Orchha", "Prithvipur"],
    "Panna": ["Panna", "Ajaigarh", "Gunour", "Pawai", "Shahnagar"],
    "Raisen": ["Raisen", "Bareli", "Begumganj", "Gairatganj", "Obaidullaganj", "Sanchi", "Silwani", "Udaipura"],
    "Rajgarh": ["Rajgarh", "Biaora", "Jirapur", "Khilchipur", "Narsinghgarh", "Pachore", "Sarangpur", "Talen"],
    "Ratlam": ["Ratlam", "Alot", "Bajna", "Jaora", "Piploda", "Sailana"],
    "Rewa": ["Rewa", "Gangev", "Gurh", "Hanumana", "Jawa", "Mauganj", "Naigarhi", "Sirmour", "Teonthar", "Tyonthar"],
    "Sagar": ["Sagar", "Banda", "Bina", "Deori", "Jaisinagar", "Khurai", "Malthone", "Rahatgarh", "Rehli", "Shahgarh"],
    "Satna": ["Satna", "Amarpatan", "Maihar", "Nagod", "Rampur Baghelan", "Ramnagar", "Uchehara", "Unchhera"],
    "Sehore": ["Sehore", "Ashta", "Budhni", "Ichhawar", "Nasrullaganj", "Rehti"],
    "Seoni": ["Seoni", "Barghat", "Chhapara", "Ghansore", "Keolari", "Kurai", "Lakhnadon"],
    "Shahdol": ["Shahdol", "Beohari", "Burhar", "Jaisinghnagar", "Jaitpur", "Sohagpur"],
    "Shajapur": ["Shajapur", "Agar", "Kalapipal", "Maksi", "Moman Badodiya", "Nalkheda", "Shujalpur", "Susner"],
    "Sheopur": ["Sheopur", "Karahal", "Vijaypur"],
    "Shivpuri": ["Shivpuri", "Badarwas", "Karera", "Khaniadhana", "Narwar", "Pichhore", "Pohri"],
    "Sidhi": ["Sidhi", "Churhat", "Deosar", "Majhauli", "Rampur Naikin", "Sihawal"],
    "Singrauli": ["Singrauli", "Chitrangi", "Devsar", "Waidhan"],
    "Tikamgarh": ["Tikamgarh", "Baldeogarh", "Jatara", "Khargapur", "Niwari", "Palera"],
    "Ujjain": ["Ujjain", "Badnagar", "Ghattia", "Khachrod", "Mahidpur", "Nagda", "Tarana"],
    "Umaria": ["Umaria", "Bandhogarh", "Manpur", "Pali"],
    "Vidisha": ["Vidisha", "Basoda", "Ganjbasoda", "Gyaraspur", "Kurwai", "Lateri", "Nateran", "Sironj"]
  },
  "Maharashtra": {
    "Ahmednagar": ["Ahmednagar", "Akole", "Jamkhed", "Karjat", "Kopargaon", "Nagar", "Nevasa", "Parner", "Pathardi", "Rahata", "Rahuri", "Sangamner", "Shevgaon", "Shrigonda", "Shrirampur"],
    "Akola": ["Akola", "Akot", "Balapur", "Barshitakli", "Murtizapur", "Patur", "Telhara"],
    "Amravati": ["Amravati", "Achalpur", "Anjangaon Surji", "Chandur Bazar", "Chandur Railway", "Chikhaldara", "Daryapur", "Dhamangaon Railway", "Dharni", "Morshi", "Nandgaon Khandeshwar", "Teosa", "Warud"],
    "Aurangabad": ["Aurangabad", "Gangapur", "Kannad", "Khuldabad", "Paithan", "Phulambri", "Sillod", "Soegaon", "Vaijapur"],
    "Beed": ["Beed", "Ambajogai", "Ashti", "Dharur", "Georai", "Kaij", "Majalgaon", "Parli", "Patoda", "Shirur Kasar", "Wadwani"],
    "Bhandara": ["Bhandara", "Lakhandur", "Lakhani", "Mohadi", "Pauni", "Sakoli", "Tumsar"],
    "Buldhana": ["Buldhana", "Chikhli", "Deulgaon Raja", "Jalgaon Jamod", "Khamgaon", "Lonar", "Malkapur", "Mehkar", "Motala", "Nandura", "Sangrampur", "Shegaon", "Sindkhed Raja"],
    "Chandrapur": ["Chandrapur", "Ballarpur", "Bhadravati", "Brahmapuri", "Chimur", "Gondpipri", "Jiwati", "Korpana", "Mul", "Nagbhid", "Pombhurna", "Rajura", "Sawali", "Sindewahi", "Warora"],
    "Dhule": ["Dhule", "Sakri", "Shirpur", "Sindkheda"],
    "Gadchiroli": ["Gadchiroli", "Aheri", "Armori", "Bhamragad", "Chamorshi", "Dhanora", "Desaiganj", "Etapalli", "Korchi", "Kurkheda", "Mulchera", "Sironcha"],
    "Gondia": ["Gondia", "Amgaon", "Arjuni Morgaon", "Deori", "Goregaon", "Sadak Arjuni", "Salekasa", "Tirora"],
    "Hingoli": ["Hingoli", "Aundha Nagnath", "Basmath", "Kalamnuri", "Sengaon"],
    "Jalgaon": ["Jalgaon", "Amalner", "Bhadgaon", "Bhusawal", "Bodwad", "Chalisgaon", "Chopda", "Dharangaon", "Erandol", "Jamner", "Muktainagar", "Pachora", "Parola", "Raver", "Yawal"],
    "Jalna": ["Jalna", "Ambad", "Badnapur", "Bhokardan", "Ghansawangi", "Jafrabad", "Mantha", "Partur"],
    "Kolhapur": ["Kolhapur", "Ajra", "Bavda", "Bhudargad", "Chandgad", "Gadhinglaj", "Hatkanangle", "Kagal", "Karvir", "Panhala", "Radhanagari", "Shahuwadi", "Shirol"],
    "Latur": ["Latur", "Ahmadpur", "Ausa", "Chakur", "Deoni", "Jalkot", "Nilanga", "Renapur", "Shirur Anantpal", "Udgir"],
    "Mumbai City": ["Mumbai City", "Colaba", "Dharavi", "Kurla", "Matunga"],
    "Mumbai Suburban": ["Andheri", "Borivali", "Kurla", "Thane"],
    "Nagpur": ["Nagpur", "Bhiwapur", "Hingna", "Kamptee", "Katol", "Kuhi", "Mauda", "Mouda", "Narkhed", "Parseoni", "Ramtek", "Savner", "Umred"],
    "Nanded": ["Nanded", "Ardhapur", "Bhokar", "Biloli", "Deglur", "Dharmabad", "Hadgaon", "Himayatnagar", "Kandhar", "Kinwat", "Loha", "Mahur", "Mudkhed", "Mukhed", "Naigaon", "Umri"],
    "Nandurbar": ["Nandurbar", "Akkalkuwa", "Akrani", "Nawapur", "Shahada", "Taloda"],
    "Nashik": ["Nashik", "Baglan", "Chandwad", "Deola", "Dindori", "Igatpuri", "Kalwan", "Malegaon", "Nandgaon", "Niphad", "Peint", "Sinnar", "Surgana", "Trimbakeshwar", "Yeola"],
    "Osmanabad": ["Osmanabad", "Bhum", "Kalamb", "Lohara", "Paranda", "Tuljapur", "Umarga", "Washi"],
    "Palghar": ["Palghar", "Dahanu", "Jawhar", "Mokhada", "Talasari", "Vasai", "Vikramgad", "Wada"],
    "Parbhani": ["Parbhani", "Gangakhed", "Jintur", "Manwath", "Palam", "Pathri", "Purna", "Sailu", "Selu", "Sonpeth"],
    "Pune": ["Pune", "Ambegaon", "Baramati", "Bhor", "Daund", "Haveli", "Indapur", "Junnar", "Khed", "Maval", "Mulshi", "Purandar", "Shirur", "Velhe"],
    "Raigad": ["Alibag", "Karjat", "Khalapur", "Mahad", "Mangaon", "Mhasla", "Murud", "Panvel", "Pen", "Poladpur", "Roha", "Shrivardhan", "Sudhagad", "Tala", "Uran"],
    "Ratnagiri": ["Ratnagiri", "Chiplun", "Dapoli", "Guhagar", "Khed", "Lanja", "Mandangad", "Rajapur", "Sangameshwar"],
    "Sangli": ["Sangli", "Atpadi", "Jat", "Kadegaon", "Kavathemahankal", "Khanapur", "Miraj", "Palus", "Shirala", "Tasgaon", "Walwa"],
    "Satara": ["Satara", "Jaoli", "Karad", "Khandala", "Khatav", "Koregaon", "Mahabaleshwar", "Man", "Patan", "Phaltan", "Wai"],
    "Sindhudurg": ["Sindhudurg", "Devgad", "Dodamarg", "Kankavli", "Kudal", "Malvan", "Sawantwadi", "Vaibhavwadi", "Vengurla"],
    "Solapur": ["Solapur", "Akkalkot", "Barshi", "Karmala", "Madha", "Malshiras", "Mangalvedhe", "Mohol", "Pandharpur", "Sangola", "South Solapur"],
    "Thane": ["Thane", "Ambarnath", "Bhiwandi", "Kalyan", "Murbad", "Shahapur", "Ulhasnagar"],
    "Wardha": ["Wardha", "Arvi", "Ashti", "Deoli", "Hinganghat", "Karanja", "Samudrapur", "Seloo", "Talegaon"],
    "Washim": ["Washim", "Karanja", "Malegaon", "Mangrulpir", "Manora", "Risod"],
    "Yavatmal": ["Yavatmal", "Arni", "Babulgaon", "Darwha", "Digras", "Ghatanji", "Kalamb", "Kelapur", "Mahagaon", "Maregaon", "Ner", "Pusad", "Ralegaon", "Umarkhed", "Wani", "Yavatmal", "Zari Jamani"]
  },
  "Manipur": {
    "Bishnupur": ["Bishnupur", "Moirang", "Nambol", "Oinam"],
    "Chandel": ["Chandel", "Chakpikarong", "Henglep", "Machi", "Moreh", "Tengnoupal"],
    "Churachandpur": ["Churachandpur", "Henglep", "Saikul", "Singhat", "Thanlon", "Tipaimukh"],
    "Imphal East": ["Imphal East", "Heingang", "Jiribam", "Khetrigao", "Lamlai", "Porompat", "Sawombung", "Wangoi"],
    "Imphal West": ["Imphal West", "Jiribam", "Lamphel", "Lilong", "Nambol", "Patsoi", "Sagolband"],
    "Jiribam": ["Jiribam"],
    "Kakching": ["Kakching", "Kakching Khunou", "Sugnu", "Wangjing"],
    "Kamjong": ["Kamjong", "Chingai", "Phungyar", "Ukhrul"],
    "Kangpokpi": ["Kangpokpi", "Jiribam", "Saitu", "Saikul"],
    "Noney": ["Noney", "Longmai", "Phalong"],
    "Pherzawl": ["Pherzawl", "Churachandpur", "Tipaimukh"],
    "Senapati": ["Senapati", "Kangpokpi", "Mao", "Paomata", "Purul"],
    "Tamenglong": ["Tamenglong", "Nungba", "Tamei", "Tousem"],
    "Tengnoupal": ["Tengnoupal", "Moreh", "Pallel"],
    "Thoubal": ["Thoubal", "Kakching", "Lilong", "Wangjing", "Yairipok"],
    "Ukhrul": ["Ukhrul", "Chingai", "Kamjong", "Phungyar", "Somi"]
  },

  "Meghalaya": {
    "East Garo Hills": ["Williamnagar", "Baghmara", "Dalu", "Resubelpara", "Rongjeng"],
    "East Jaintia Hills": ["Khliehriat", "Amlarem", "Laskein", "Saipung"],
    "East Khasi Hills": ["Shillong", "Cherrapunjee", "Mawkyrwat", "Mawlai", "Mawphlang", "Mawryngkneng", "Mawsynram", "Pynursla", "Shella Bholaganj", "Sohra"],
    "North Garo Hills": ["Resubelpara", "Bajengdoba", "Mendipathar"],
    "Ri Bhoi": ["Nongpoh", "Jirang", "Nongstoin", "Umsning", "Umiam"],
    "South Garo Hills": ["Baghmara", "Chokpot", "Mahendraganj"],
    "South West Garo Hills": ["Ampati", "Betasing", "Tikrikilla"],
    "South West Khasi Hills": ["Mawkyrwat", "Ranikor"],
    "West Garo Hills": ["Tura", "Dalu", "Dadenggre", "Gambegre", "Phulbari", "Rongram", "Selsella", "Tikrikilla"],
    "West Jaintia Hills": ["Jowai", "Laskein", "Thadlaskein"],
    "West Khasi Hills": ["Nongstoin", "Mairang", "Mawkyrwat", "Nongstoin", "Ranikor"]
  },

  "Mizoram": {
    "Aizawl": ["Aizawl", "Darlawn", "Phullen", "Saitual", "Thingsulthliah"],
    "Champhai": ["Champhai", "Khawzawl", "Ngopa"],
    "Hnahthial": ["Hnahthial", "Lungsen"],
    "Khawzawl": ["Khawzawl", "Ngopa"],
    "Kolasib": ["Kolasib", "Bilkhawthlir", "Thingdawl"],
    "Lawngtlai": ["Lawngtlai", "Chawngte", "Sangau"],
    "Lunglei": ["Lunglei", "Bunghmun", "Hnahthial", "Lungsen", "Tlabung", "Tuipang"],
    "Mamit": ["Mamit", "Kawrthah", "Phaileng", "West Phaileng"],
    "Saiha": ["Saiha", "Tuipang"],
    "Saitual": ["Saitual"],
    "Serchhip": ["Serchhip", "E Lungdar", "Thenzawl"]
  },

  "Nagaland": {
    "Chumoukedima": ["Chumoukedima", "Dimapur"],
    "Dimapur": ["Dimapur", "Chumoukedima", "Medziphema"],
    "Kiphire": ["Kiphire", "Pungro", "Seyochung"],
    "Kohima": ["Kohima", "Chiephobozou", "Jakhama", "Kezocha", "Kigwema", "Phek", "Tseminyu"],
    "Longleng": ["Longleng", "Tamlu"],
    "Mokokchung": ["Mokokchung", "Changtongya", "Chuchuyimlang", "Longchem", "Mangkolemba", "Tuli", "Tzudikong"],
    "Mon": ["Mon", "Aboi", "Mopungchuket", "Naginimora", "Tizit", "Tobu"],
    "Niuland": ["Niuland"],
    "Noklak": ["Noklak", "Shamator"],
    "Peren": ["Peren", "Jalukie", "Tening"],
    "Phek": ["Phek", "Chozuba", "Meluri", "Pfutsero"],
    "Shamator": ["Shamator", "Noklak"],
    "Tseminyu": ["Tseminyu"],
    "Tuensang": ["Tuensang", "Noksen", "Shamator", "Tobu"],
    "Wokha": ["Wokha", "Bhandari", "Sanis"],
    "Zunheboto": ["Zunheboto", "Aghunato", "Akuluto", "Satoi"]
  },

  "Odisha": {
    "Angul": ["Angul", "Athamallik", "Banarpal", "Chhendipada", "Kaniha", "Pallahara", "Talcher"],
    "Balangir": ["Balangir", "Agalpur", "Belpara", "Deogaon", "Gudvella", "Kantabanji", "Loisingha", "Muribahal", "Patnagarh", "Saintala", "Titilagarh", "Tureikela"],
    "Balasore": ["Balasore", "Bahanaga", "Baliapal", "Basta", "Bhograi", "Jaleswar", "Nilgiri", "Oupada", "Remuna", "Simulia", "Soro"],
    "Bargarh": ["Bargarh", "Ambabhona", "Attabira", "Barpali", "Bijepur", "Bhatli", "Gaisilet", "Jharbandh", "Padampur", "Paikmal", "Sohela"],
    "Bhadrak": ["Bhadrak", "Basudevpur", "Bhandaripokhari", "Bonth", "Chandbali", "Dhamnagar", "Tihidi"],
    "Bolangir": ["Bolangir", "Kantabanji", "Patnagarh", "Titilagarh"],
    "Boudh": ["Boudh", "Baunsuni", "Harbhanga", "Kantamal"],
    "Cuttack": ["Cuttack", "Athagarh", "Banki", "Baramba", "Barang", "Dampara", "Kantapada", "Mahanga", "Narasinghpur", "Niali", "Salepur", "Tangi"],
    "Deogarh": ["Deogarh", "Barkote", "Reamal", "Tileibani"],
    "Dhenkanal": ["Dhenkanal", "Bhuban", "Gondia", "Hindol", "Kamakhyanagar", "Odapada", "Parjang"],
    "Gajapati": ["Paralakhemundi", "Guma", "Kashinagar", "Mohana", "R.Udayagiri", "Rayagada"],
    "Ganjam": ["Berhampur", "Aska", "Bhanjanagar", "Buguda", "Chhatrapur", "Chikiti", "Digapahandi", "Hinjilicut", "Kabisuryanagar", "Khallikote", "Kodala", "Kukudakhandi", "Patrapur", "Polasara", "Purusottampur", "Rangeilunda", "Sanakhemundi", "Sheragada", "Sorada"],
    "Jagatsinghpur": ["Jagatsinghpur", "Balikuda", "Biridi", "Borikina", "Erasama", "Kujang", "Naugaon", "Raghunathpur", "Tirtol"],
    "Jajpur": ["Jajpur", "Barchana", "Bari", "Basudevpur", "Biridi", "Danagadi", "Dharmasala", "Korei", "Rasulpur", "Sukinda"],
    "Jharsuguda": ["Jharsuguda", "Belpahar", "Brajarajnagar", "Kolabira", "Lakhanpur"],
    "Kalahandi": ["Bhawanipatna", "Dharmagarh", "Junagarh", "Kalampur", "Kesinga", "Lanjigarh", "M.Rampur", "Narla", "Thuamul Rampur"],
    "Kandhamal": ["Phulbani", "Baliguda", "Chakapada", "G.Udayagiri", "Khajuripada", "Kotagarh", "Phiringia", "Raikia", "Tikabali", "Tumudibandha"],
    "Kendrapara": ["Kendrapara", "Aul", "Derabish", "Garadpur", "Mahakalapada", "Marshaghai", "Pattamundai", "Rajkanika", "Rajnagar"],
    "Kendujhar": ["Kendujhar", "Anandapur", "Barbil", "Banspal", "Champua", "Ghasipura", "Harichandanpur", "Joda", "Jhumpura", "Telkoi"],
    "Khordha": ["Bhubaneswar", "Balianta", "Balipatna", "Banpur", "Bolagarh", "Chilika", "Jatni", "Khordha", "Tangi"],
    "Koraput": ["Koraput", "Baipariguda", "Bandhugaon", "Boipariguda", "Dasmantpur", "Jeypore", "Kotpad", "Laxmipur", "Machkund", "Narayanpatna", "Nandapur", "Pottangi", "Similiguda"],
    "Malkangiri": ["Malkangiri", "Chitrakonda", "Kalimela", "Korkunda", "Kudumuluguma", "Mathili", "Podia"],
    "Mayurbhanj": ["Baripada", "Badasahi", "Bangriposi", "Bisoi", "Jashipur", "Karanjia", "Khunta", "Morada", "Rairangpur", "Saraskana", "Suliapada", "Tiring", "Udala"],
    "Nabarangpur": ["Nabarangpur", "Chandahandi", "Dabugam", "Jharigaon", "Kosagumuda", "Nandahandi", "Papadahandi", "Raighar", "Tentulikhunti", "Umerkote"],
    "Nayagarh": ["Nayagarh", "Bhapur", "Daspalla", "Gania", "Khandapara", "Nuagaon", "Odagaon", "Ranpur"],
    "Nuapada": ["Nuapada", "Boden", "Khariar", "Komna", "Sinapali"],
    "Puri": ["Puri", "Astaranga", "Brahmagiri", "Delang", "Gop", "Kakatpur", "Kanas", "Konark", "Krushnaprasad", "Nimapara", "Pipili", "Satyabadi", "Sadar"],
    "Rayagada": ["Rayagada", "Bissamcuttack", "Gudari", "Gunupur", "Kashipur", "Kolnara", "Muniguda", "Padampur", "Ramanaguda", "Tikiri"],
    "Sambalpur": ["Sambalpur", "Bamra", "Jamankira", "Jujumura", "Kuchinda", "Maneswar", "Naktideul", "Rairakhol", "Rengali"],
    "Subarnapur": ["Sonepur", "Birmaharajpur", "Binka", "Dunguripali", "Tarbha", "Ullunda"],
    "Sundargarh": ["Sundargarh", "Bargaon", "Bisra", "Bonai", "Gurundia", "Hemgir", "Koira", "Kuanrmunda", "Kutra", "Lahunipara", "Lathikata", "Nuagaon", "Rajgangpur", "Subdega", "Tangarpali"]
  },

  "Puducherry": {
    "Karaikal": ["Karaikal", "Kottucherry", "Neravy", "Thirunallar"],
    "Mahe": ["Mahe"],
    "Puducherry": ["Puducherry", "Ariyankuppam", "Bahour", "Mannadipet", "Nettapakkam", "Ozhukarai", "Villianur"],
    "Yanam": ["Yanam"]
  },

  "Punjab": {
    "Amritsar": ["Amritsar", "Ajnala", "Baba Bakala", "Majitha", "Tarn Taran"],
    "Barnala": ["Barnala", "Dhanaula", "Mehal Kalan"],
    "Bathinda": ["Bathinda", "Goniana", "Nathana", "Phul", "Rampura Phul", "Sangat", "Talwandi Sabo"],
    "Faridkot": ["Faridkot", "Jaitu", "Kotkapura"],
    "Fatehgarh Sahib": ["Fatehgarh Sahib", "Amloh", "Bassi Pathana", "Khamanon", "Morinda"],
    "Fazilka": ["Fazilka", "Abohar", "Jalalabad"],
    "Ferozepur": ["Ferozepur", "Fazilka", "Guru Har Sahai", "Jalalabad", "Zira"],
    "Gurdaspur": ["Gurdaspur", "Batala", "Dina Nagar", "Dhariwal", "Dera Baba Nanak", "Fatehgarh Churian", "Kahnuwan", "Pathankot", "Qadian"],
    "Hoshiarpur": ["Hoshiarpur", "Bhunga", "Dasuya", "Garhshankar", "Hajipur", "Mahilpur", "Mukerian", "Tanda"],
    "Jalandhar": ["Jalandhar", "Adampur", "Bhogpur", "Lohian", "Nakodar", "Nawanshahr", "Phillaur", "Shahkot"],
    "Kapurthala": ["Kapurthala", "Dhilwan", "Nadala", "Phagwara", "Sultanpur Lodhi"],
    "Ludhiana": ["Ludhiana", "Dehlon", "Jagraon", "Khanna", "Machhiwara", "Payal", "Raikot", "Samrala"],
    "Malerkotla": ["Malerkotla", "Ahmedgarh"],
    "Mansa": ["Mansa", "Bareta", "Bhikhi", "Budhlada", "Sardulgarh"],
    "Moga": ["Moga", "Baghapurana", "Dharamkot", "Nihal Singh Wala"],
    "Mohali": ["Mohali", "Derabassi", "Kharar", "Kurali"],
    "Muktsar": ["Muktsar", "Gidderbaha", "Lambi", "Malout"],
    "Pathankot": ["Pathankot", "Dhar Kalan", "Narot Jaimal Singh"],
    "Patiala": ["Patiala", "Ghanaur", "Nabha", "Patran", "Rajpura", "Samana", "Sanour"],
    "Rupnagar": ["Rupnagar", "Anandpur Sahib", "Chamkaur Sahib", "Kiratpur Sahib", "Morinda", "Nurpur Bedi"],
    "Sangrur": ["Sangrur", "Andana", "Bhawanigarh", "Dhuri", "Dirba", "Lehra", "Longowal", "Malerkotla", "Moonak", "Sunam"],
    "Shahid Bhagat Singh Nagar": ["Nawanshahr", "Balachaur", "Banga"],
    "Tarn Taran": ["Tarn Taran", "Khem Karan", "Patti", "Pul Kanjri", "Sursingh"]
  },

  "Rajasthan": {
    "Ajmer": ["Ajmer", "Arai", "Beawar", "Bhinai", "Jawaja", "Kekri", "Kishangarh", "Masuda", "Nasirabad", "Peesangan", "Pisangan", "Pushkar", "Roopangarh", "Sawar", "Srinagar"],
    "Alwar": ["Alwar", "Bansur", "Behror", "Kathumar", "Kishangarh Bas", "Kotkasim", "Lachhmangarh", "Mandawar", "Mundawar", "Neemrana", "Rajgarh", "Ramgarh", "Tapukara", "Thanagazi", "Tijara"],
    "Banswara": ["Banswara", "Anandpuri", "Bagidora", "Ghatol", "Garhi", "Kushalgarh", "Sajjangarh"],
    "Baran": ["Baran", "Anta", "Atru", "Chabra", "Chipa Barod", "Kishanganj", "Mangrol", "Shahabad"],
    "Barmer": ["Barmer", "Balotra", "Baytu", "Chohtan", "Dhorimanna", "Gadra Road", "Gudamalani", "Pachpadra", "Ramsar", "Sheo", "Siwana"],
    "Bharatpur": ["Bharatpur", "Bayana", "Deeg", "Kaman", "Kumher", "Nadbai", "Nagar", "Pahari", "Roopwas", "Sewar", "Sikri", "Weir"],
    "Bhilwara": ["Bhilwara", "Asind", "Banera", "Gangapur", "Hurda", "Jahazpur", "Kotri", "Mandal", "Mandalgarh", "Phuliya Kalan", "Raipur", "Sahara", "Shahpura", "Suwana"],
    "Bikaner": ["Bikaner", "Bajju", "Chhatargarh", "Colayat", "Deshnok", "Dungargarh", "Khajuwala", "Lunkaransar", "Nokha", "Poogal", "Pugal"],
    "Bundi": ["Bundi", "Hindoli", "Indergarh", "Keshoraipatan", "Nainwa", "Talera"],
    "Chittorgarh": ["Chittorgarh", "Bari Sadri", "Begun", "Bhadesar", "Bhupalsagar", "Dungla", "Gangrar", "Kapasan", "Nimbahera", "Pratapgarh", "Rashmi", "Rawatbhata"],
    "Churu": ["Churu", "Rajgarh", "Ratangarh", "Sadulpur", "Sardarshahar", "Sujangarh", "Taranagar"],
    "Dausa": ["Dausa", "Bandikui", "Baswa", "Lalsot", "Mahwa", "Nangal Rajawatan", "Sikrai"],
    "Dholpur": ["Dholpur", "Bari", "Baseri", "Rajakhera", "Saramathura"],
    "Dungarpur": ["Dungarpur", "Aspur", "Bichhiwara", "Chikhali", "Dovda", "Galiyakot", "Sagwara", "Simalwara"],
    "Ganganagar": ["Ganganagar", "Anupgarh", "Gharsana", "Karanpur", "Padampur", "Raisinghnagar", "Sadulshahar", "Suratgarh", "Vijaynagar"],
    "Hanumangarh": ["Hanumangarh", "Bhadra", "Nohar", "Pilibanga", "Rawatsar", "Sangaria", "Tibbi"],
    "Jaipur": ["Jaipur", "Amber", "Bassi", "Chaksu", "Chomu", "Dudu", "Jamwa Ramgarh", "Jhotwara", "Kotputli", "Phagi", "Phulera", "Sanganer", "Shahpura", "Viratnagar"],
    "Jaisalmer": ["Jaisalmer", "Fatehgarh", "Pokaran", "Ramgarh", "Sam", "Sankra"],
    "Jalore": ["Jalore", "Ahore", "Bhinmal", "Chitalwana", "Jaswantpura", "Raniwara", "Sanchore", "Siwana"],
    "Jhalawar": ["Jhalawar", "Aklera", "Bakani", "Bhawani Mandi", "Dag", "Gangdhar", "Jhalarapatan", "Khanpur", "Manoharthana", "Pirawa"],
    "Jhunjhunu": ["Jhunjhunu", "Buhana", "Chirawa", "Khetri", "Malsisar", "Nawalgarh", "Pilani", "Surajgarh", "Udaipurwati"],
    "Jodhpur": ["Jodhpur", "Bap", "Baori", "Bhopalgarh", "Bilara", "Lohawat", "Luni", "Mandore", "Osian", "Phalodi", "Pipar City", "Shergarh", "Tinwari"],
    "Karauli": ["Karauli", "Hindaun", "Mandrayal", "Nadoti", "Sapotra", "Shri Mahaveerji", "Todabhim"],
    "Kota": ["Kota", "Digod", "Itawa", "Kanwas", "Ladpura", "Pipalda", "Ramganj Mandi", "Sangod"],
    "Nagaur": ["Nagaur", "Degana", "Didwana", "Jayal", "Khinvsar", "Ladnun", "Makrana", "Merta City", "Mundwa", "Nawa", "Parbatsar", "Riyan Badi"],
    "Pali": ["Pali", "Bali", "Desuri", "Jaitaran", "Marwar Junction", "Raipur", "Rohat", "Sojat", "Sumerpur"],
    "Pratapgarh": ["Pratapgarh", "Arnod", "Chhoti Sadri", "Dhariawad", "Peepal Khoont"],
    "Rajsamand": ["Rajsamand", "Amet", "Bhim", "Deogarh", "Kankroli", "Khamnor", "Nathdwara", "Railmagra", "Relmagra"],
    "Sawai Madhopur": ["Sawai Madhopur", "Bamanwas", "Bonli", "Gangapur City", "Khandar", "Malarna Dungar", "Wazirpur"],
    "Sikar": ["Sikar", "Danta Ramgarh", "Dhod", "Fatehpur", "Khandela", "Lachhmangarh", "Neem Ka Thana", "Piprali", "Ramgarh Shekhawati", "Shrimadhopur", "Sri Madhopur"],
    "Sirohi": ["Sirohi", "Abu Road", "Pindwara", "Reodar", "Sheoganj"],
    "Tonk": ["Tonk", "Deoli", "Malpura", "Niwai", "Peeplu", "Todaraisingh", "Uniara"],
    "Udaipur": ["Udaipur", "Girwa", "Gogunda", "Jhadol", "Kherwara", "Kotra", "Lasadiya", "Mavli", "Sarada", "Salumbar", "Vallabhnagar"]
  },
  "Sikkim": {
    "East Sikkim": ["Gangtok", "Pakyong", "Rangpo", "Rongli", "Singtam"],
    "North Sikkim": ["Mangan", "Chungthang", "Dzongu", "Lachen", "Lachung"],
    "South Sikkim": ["Namchi", "Jorethang", "Melli", "Ravangla", "Temi"],
    "West Sikkim": ["Gyalshing", "Dentam", "Kaluk", "Soreng", "Yuksom"]
  },

  "Tamil Nadu": {
    "Ariyalur": ["Ariyalur", "Andimadam", "Jayankondam", "Sendurai", "T.Palur", "Udayarpalayam"],
    "Chengalpattu": ["Chengalpattu", "Cheyyur", "Maduranthakam", "Maraimalai Nagar", "Thiruporur", "Tirukalukundram"],
    "Chennai": ["Chennai", "Ambattur", "Alandur", "Egmore", "Kodambakkam", "Perambur", "Royapuram", "Sholinganallur", "T Nagar", "Tondiarpet"],
    "Coimbatore": ["Coimbatore", "Annur", "Kinathukadavu", "Mettupalayam", "Perur", "Pollachi", "Sulur", "Valparai"],
    "Cuddalore": ["Cuddalore", "Bhuvanagiri", "Chidambaram", "Kattumannarkoil", "Kurinjipadi", "Panruti", "Srimushnam", "Tittagudi", "Virudhachalam"],
    "Dharmapuri": ["Dharmapuri", "Harur", "Karimangalam", "Nallampalli", "Palacode", "Pennagaram"],
    "Dindigul": ["Dindigul", "Attur", "Gujiliamparai", "Kodaikanal", "Natham", "Nilakottai", "Oddanchatram", "Palani", "Reddiyarchatram", "Vedasandur"],
    "Erode": ["Erode", "Anthiyur", "Bhavani", "Gobichettipalayam", "Kodumudi", "Modakurichi", "Nambiyur", "Perundurai", "Sathyamangalam"],
    "Kallakurichi": ["Kallakurichi", "Chinnasalem", "Kalvarayan Hills", "Sankarapuram", "Tirukoilur", "Ulundurpet"],
    "Kancheepuram": ["Kancheepuram", "Kancheepuram", "Sriperumbudur", "Uthiramerur", "Walajabad"],
    "Kanyakumari": ["Nagercoil", "Agastheeswaram", "Kalkulam", "Killiyoor", "Thovalai", "Vilavancode"],
    "Karur": ["Karur", "Aravakurichi", "Kadavur", "Krishnarayapuram", "Kulithalai", "Manmangalam"],
    "Krishnagiri": ["Krishnagiri", "Bargur", "Denkanikottai", "Hosur", "Kaveripattinam", "Pochampalli", "Shoolagiri", "Uthangarai", "Veppanapalli"],
    "Madurai": ["Madurai", "Kalligudi", "Madurai East", "Madurai North", "Madurai South", "Madurai West", "Melur", "Peraiyur", "Thirumangalam", "Usilampatti", "Vadipatti"],
    "Mayiladuthurai": ["Mayiladuthurai", "Kuthalam", "Sirkali", "Tharangambadi"],
    "Nagapattinam": ["Nagapattinam", "Kilvelur", "Kollidam", "Mayiladuthurai", "Sirkazhi", "Tharangambadi", "Vedaranyam"],
    "Namakkal": ["Namakkal", "Kolli Hills", "Kumarapalayam", "Mohanur", "Paramathi Velur", "Rasipuram", "Sendamangalam", "Tiruchengode"],
    "Nilgiris": ["Udhagamandalam", "Coonoor", "Gudalur", "Kotagiri", "Kundah", "Pandalur"],
    "Perambalur": ["Perambalur", "Alathur", "Kunnam", "Veppanthattai"],
    "Pudukkottai": ["Pudukkottai", "Alangudi", "Aranthangi", "Avudayarkoil", "Gandarvakottai", "Iluppur", "Karambakudi", "Kulathur", "Manamelkudi", "Ponnamaravathi", "Thiruvarankulam", "Tirumayam", "Viralimalai"],
    "Ramanathapuram": ["Ramanathapuram", "Kadaladi", "Kamuthi", "Mudukulathur", "Paramakudi", "Rajasingamangalam", "Rameswaram", "Tiruvadanai"],
    "Ranipet": ["Ranipet", "Arakkonam", "Arcot", "Nemili", "Sholinghur", "Walajah"],
    "Salem": ["Salem", "Attur", "Edappadi", "Gangavalli", "Mettur", "Omalur", "Pethanaickenpalayam", "Sankari", "Valapady", "Yercaud"],
    "Sivaganga": ["Sivaganga", "Devakottai", "Ilayangudi", "Kalaiyarkoil", "Karaikudi", "Manamadurai", "Singampunari", "Tiruppattur"],
    "Tenkasi": ["Tenkasi", "Alangulam", "Kadayanallur", "Sankarankovil", "Shencottai", "Sivagiri", "Veerakeralampudur"],
    "Thanjavur": ["Thanjavur", "Budalur", "Kumbakonam", "Orathanadu", "Papanasam", "Pattukkottai", "Peravurani", "Thiruvaiyaru", "Thiruvidaimarudur"],
    "Theni": ["Theni", "Andipatti", "Bodinayakanur", "Periyakulam", "Uthamapalayam"],
    "Thoothukudi": ["Thoothukudi", "Ettayapuram", "Kovilpatti", "Ottapidaram", "Sathankulam", "Srivaikundam", "Tiruchendur", "Vilathikulam"],
    "Tiruchirappalli": ["Tiruchirappalli", "Lalgudi", "Manachanallur", "Manapparai", "Marungapuri", "Musiri", "Srirangam", "Thottiyam", "Thuraiyur", "Tiruverumbur"],
    "Tirunelveli": ["Tirunelveli", "Ambasamudram", "Cheranmahadevi", "Manur", "Nanguneri", "Palayamkottai", "Radhapuram", "Tenkasi", "Tirunelveli"],
    "Tirupathur": ["Tirupathur", "Ambur", "Jolarpet", "Natrampalli", "Vaniyambadi"],
    "Tiruppur": ["Tiruppur", "Avinashi", "Dharapuram", "Gudimangalam", "Kangeyam", "Madathukulam", "Palladam", "Udumalaipettai", "Uthukuli"],
    "Tiruvallur": ["Tiruvallur", "Avadi", "Gummidipoondi", "Ponneri", "Poonamallee", "R.K.Pet", "Tiruttani", "Uthukkottai"],
    "Tiruvannamalai": ["Tiruvannamalai", "Arni", "Chengam", "Chetpet", "Jamunamarathur", "Kalasapakkam", "Kilpennathur", "Polur", "Thellar", "Vandavasi", "Vembakkam"],
    "Tiruvarur": ["Tiruvarur", "Kodavasal", "Mannargudi", "Nannilam", "Needamangalam", "Papanasam", "Thiruthuraipoondi", "Valangaiman"],
    "Vellore": ["Vellore", "Anaicut", "Gudiyatham", "Katpadi", "Pernambut", "Tirupathur", "Vaniyambadi"],
    "Viluppuram": ["Viluppuram", "Gingee", "Kallakurichi", "Marakanam", "Melmalaiyanur", "Mugaiyur", "Rishivandiyam", "Sankarapuram", "Tindivanam", "Tirukoilur", "Ulundurpet", "Vanur"],
    "Virudhunagar": ["Virudhunagar", "Aruppukkottai", "Kariapatti", "Rajapalayam", "Sivakasi", "Srivilliputhur", "Tiruchuli", "Vembakottai", "Watrap"]
  },

  "Telangana": {
    "Adilabad": ["Adilabad", "Bazarhathnoor", "Bela", "Boath", "Gudihatnoor", "Ichoda", "Jainath", "Mavala", "Narnoor", "Tamsi", "Utnoor"],
    "Bhadradri Kothagudem": ["Kothagudem", "Aswaraopeta", "Bayyaram", "Burgampahad", "Cherla", "Dammapeta", "Julurpad", "Laxmidevipally", "Manuguru", "Mulkalapally", "Palvancha", "Pinapaka", "Sujathanagar", "Tekulapally", "Yellandu"],
    "Hanamkonda": ["Hanamkonda", "Geesugonda", "Hasanparthy", "Parkal", "Sangem"],
    "Hyderabad": ["Hyderabad", "Amberpet", "Bandlaguda", "Charminar", "Golconda", "Khairatabad", "Secunderabad", "Uppal"],
    "Jagtial": ["Jagtial", "Dharmapuri", "Gollapalli", "Koratla", "Mallial", "Metpally", "Pegadapally", "Raikal", "Sarangapur"],
    "Jangaon": ["Jangaon", "Bachannapeta", "Devaruppula", "Ghanpur", "Kodakandla", "Lingalaghanpur", "Narmetta", "Palakurthi", "Raghunathpally", "Zaffergadh"],
    "Jayashankar Bhupalpally": ["Bhupalpally", "Chityal", "Eturnagaram", "Kataram", "Mahadevpur", "Manthani", "Mogullapally", "Palimela", "Regonda", "Tekumatla"],
    "Jogulamba Gadwal": ["Gadwal", "Alampur", "Ayijapur", "Dharur", "Gattu", "Ieeja", "Itikyal", "Maldakal", "Rajoli", "Waddepally"],
    "Kamareddy": ["Kamareddy", "Banswada", "Bheemgal", "Bhiknoor", "Domakonda", "Ellareddy", "Jukkal", "Lingampet", "Machareddy", "Madnoor", "Nizamsagar", "Pitlam", "Ramareddy", "Saakoor", "Yellareddy"],
    "Karimnagar": ["Karimnagar", "Choppadandi", "Gangadhara", "Huzurabad", "Husnabad", "Jagtial", "Julapally", "Kothapally", "Manakondur", "Manthani", "Ramadugu", "Saidapur", "Shankarapatnam", "Thimmapur", "Veenavanka"],
    "Khammam": ["Khammam", "Bonakal", "Enkoor", "Kallur", "Khammam Rural", "Konijerla", "Kusumanchi", "Madhira", "Mudigonda", "Nelakondapally", "Penuballi", "Sattupally", "Thirumalayapalem", "Vemsoor", "Wyra"],
    "Kumuram Bheem Asifabad": ["Asifabad", "Ankoli", "Bejjur", "Dahegaon", "Jainoor", "Kagaznagar", "Kerameri", "Kouthala", "Narnoor", "Rebbena", "Sirpur"],
    "Mahabubabad": ["Mahabubabad", "Bayyaram", "Chinnagudur", "Dornakal", "Garla", "Gudur", "Kesamudram", "Kuravi", "Maripeda", "Narsimhulapet", "Nellikudur", "Thorrur"],
    "Mahabubnagar": ["Mahabubnagar", "Achampet", "Addakal", "Amangal", "Balanagar", "Bhoothpur", "Bijinapally", "Chinnachintakunta", "Devarkadra", "Dhanwada", "Farooqnagar", "Gadwal", "Hanwada", "Jadcherla", "Kalwakurthy", "Kodangal", "Kollapur", "Kosgi", "Makthal", "Midjil", "Nagarkurnool", "Narayanpet", "Peddamandadi", "Shadnagar", "Utkoor", "Veldanda", "Wanaparthy"],
    "Mancherial": ["Mancherial", "Bellampally", "Bheemini", "Chennur", "Dandepally", "Hajipur", "Jaipur", "Jannaram", "Kannepally", "Kasipet", "Kotapally", "Luxettipet", "Mandamarri", "Naspur", "Neredigonda", "Ramakrishnapur", "Tandur"],
    "Medak": ["Medak", "Alladurg", "Chegunta", "Dubbak", "Gajwel", "Havelighanpur", "Jogipet", "Kohir", "Kulcharam", "Narsapur", "Papannapet", "Ramayampet", "Shankarampet", "Siddipet", "Tekmal", "Toopran", "Yeldurthy"],
    "Medchal-Malkajgiri": ["Medchal", "Bahadurpally", "Dundigal", "Ghatkesar", "Keesara", "Kompally", "Malkajgiri", "Medipally", "Quthbullapur", "Shamirpet", "Uppal"],
    "Mulugu": ["Mulugu", "Eturnagaram", "Govindaraopet", "Mangapet", "Tadvai", "Venkatapur", "Wazeedu"],
    "Nagarkurnool": ["Nagarkurnool", "Achampet", "Bijinapally", "Charakonda", "Kalwakurthy", "Kollapur", "Lingal", "Padara", "Tadoor", "Telkapally", "Utkoor", "Veldanda"],
    "Nalgonda": ["Nalgonda", "Addakal", "Alair", "Bhongir", "Chandur", "Choutuppal", "Devarakonda", "Huzurnagar", "Kodad", "Marriguda", "Miryalaguda", "Munugode", "Nakrekal", "Narayanpuram", "Nidamanur", "Pedda Adiserla Pally", "Ramannapeta", "Suryapet", "Thipparthi", "Tirumalgiri", "Tungaturthy"],
    "Narayanpet": ["Narayanpet", "Kosgi", "Maddur", "Maganoor", "Marikal"],
    "Nirmal": ["Nirmal", "Bhainsa", "Dilawarpur", "Kaddam", "Khanapur", "Kubeer", "Laxmanchanda", "Lokeswaram", "Mamda", "Mudhole", "Narsapur", "Sarangapur"],
    "Nizamabad": ["Nizamabad", "Armoor", "Balkonda", "Banswada", "Bheemgal", "Bodhan", "Dichpally", "Domakonda", "Indalwai", "Jakranpally", "Kamareddy", "Kotagiri", "Kotgiri", "Lingampet", "Madnoor", "Makloor", "Mosra", "Navipet", "Nizam Sagar", "Pitlam", "Renjal", "Sirkonda", "Varni", "Yellareddy", "Yedapally"],
    "Peddapalli": ["Peddapalli", "Dharmaram", "Eligedu", "Julapally", "Kalwapally", "Karimnagar", "Kataram", "Manthani", "Odela", "Ramagundam", "Sultanabad"],
    "Rajanna Sircilla": ["Sircilla", "Boinpally", "Chandurthi", "Cheriyal", "Ellanthakunta", "Gambhiraopet", "Koheda", "Mustabad", "Rudrangi", "Thangallapally", "Vemulawada"],
    "Rangareddy": ["Rangareddy", "Chevella", "Farooqnagar", "Hayathnagar", "Ibrahimpatnam", "Kandukur", "Kothur", "Maheshwaram", "Manchal", "Marpally", "Rajendranagar", "Shadnagar", "Shankarpally", "Tandur", "Vikarabad"],
    "Sangareddy": ["Sangareddy", "Andole", "Hathnoora", "Jogipet", "Kohir", "Kondapur", "Kulcharam", "Manoor", "Narayankhed", "Nyalkal", "Patancheru", "Pulkal", "Ramachandrapuram", "Sadasivpet", "Vatpally", "Zahirabad"],
    "Siddipet": ["Siddipet", "Cheriyal", "Dubbak", "Gajwel", "Husnabad", "Koheda", "Kondapak", "Mirdoddi", "Nangnoor", "Thoguta", "Wargal"],
    "Suryapet": ["Suryapet", "Atmakur", "Chivvemla", "Huzurnagar", "Kodad", "Mothkur", "Munagala", "Nalgonda", "Nampally", "Nereducharla", "Penpahad", "Thirumalagiri", "Tungaturthy"],
    "Vikarabad": ["Vikarabad", "Basheerabad", "Bomraspet", "Doma", "Kodangal", "Kulkacherla", "Marpally", "Nawabpet", "Pargi", "Pudur", "Tandur"],
    "Wanaparthy": ["Wanaparthy", "Atmakur", "Chinnambavi", "Gopalpet", "Kothakota", "Madanapur", "Peddamandadi", "Pebbair", "Reddypalem", "Srirangapur"],
    "Warangal Rural": ["Warangal Rural", "Atmakur", "Cherial", "Chityal", "Duggondi", "Geesugonda", "Hasanparthy", "Khanapur", "Narsampet", "Nekkonda", "Parkal", "Parvathagiri", "Sangem", "Shayampet", "Wardhannapeta"],
    "Warangal Urban": ["Warangal", "Dharmasagar", "Elkathurthy", "Geesugonda", "Hanamkonda", "Hasanparthy", "Kazipet", "Nallabelly", "Parkal", "Sangem", "Wardhannapet"],
    "Yadadri Bhuvanagiri": ["Bhuvanagiri", "Alair", "Aler", "Atmakur", "Bibinagar", "Bhongir", "Choutuppal", "Mothkur", "Narayanpuram", "Rajapet", "Ramannapet", "Turkapally", "Yadagirigutta"]
  },

  "Tripura": {
    "Dhalai": ["Ambassa", "Gandacherra", "Kamalpur", "Longtharai Valley", "Manu", "Salema"],
    "Gomati": ["Udaipur", "Amarpur", "Karbook", "Killa", "Matabari", "Ompi", "Silachari"],
    "Khowai": ["Khowai", "Kalyanpur", "Mungiakami", "Padmabil", "Teliamura"],
    "North Tripura": ["Dharmanagar", "Dasda", "Jubarajnagar", "Kanchanpur", "Kumarghat", "Panisagar"],
    "Sepahijala": ["Bishalgarh", "Boxanagar", "Charilam", "Jampuijala", "Melaghar", "Sonamura"],
    "South Tripura": ["Belonia", "Bagafa", "Hrishyamukh", "Jolaibari", "Rajnagar", "Sabroom", "Satchand", "Shantirbazar"],
    "Unakoti": ["Kailashahar", "Chandipur", "Kumarghat", "Pecharthal"],
    "West Tripura": ["Agartala", "Bisramganj", "Dukli", "Jirania", "Majlishpur", "Mohanpur", "Padmabil", "Ramchandraghat"]
  },
  "Uttar Pradesh": {
    "Agra": ["Agra", "Bah", "Etmadpur", "Fatehabad", "Kheragarh", "Kiraoli", "Saiyan"],
    "Aligarh": ["Aligarh", "Atrauli", "Bijauli", "Chandaus", "Gabhana", "Iglas", "Jawan", "Khair", "Koil", "Tappal"],
    "Ambedkar Nagar": ["Akbarpur", "Allapur", "Bhiti", "Jalalpur", "Tanda"],
    "Amethi": ["Amethi", "Gauriganj", "Jagdishpur", "Musafirkhana", "Sangrampur", "Tiloi"],
    "Amroha": ["Amroha", "Dhanaura", "Gajraula", "Hasanpur", "Naugawan Sadat"],
    "Auraiya": ["Ajitmal", "Auraiya", "Bidhuna", "Dibiyapur"],
    "Ayodhya": ["Ayodhya", "Bikapur", "Faizabad", "Milkipur", "Rudauli", "Sohawal"],
    "Azamgarh": ["Azamgarh", "Atraulia", "Burhanpur", "Lalganj", "Mehnagar", "Nizamabad", "Phulpur", "Sagri"],
    "Baghpat": ["Baghpat", "Baraut", "Khekada"],
    "Bahraich": ["Bahraich", "Kaiserganj", "Mahasi", "Nanpara", "Payagpur", "Shivpur"],
    "Ballia": ["Ballia", "Bairia", "Bansdih", "Belthara Road", "Rasra", "Sikanderpur"],
    "Balrampur": ["Balrampur", "Gaisari", "Tulsipur", "Utraula"],
    "Banda": ["Banda", "Atarra", "Baberu", "Naraini", "Pailani", "Tindwari"],
    "Bara Banki": ["Bara Banki", "Fatehpur", "Haidergarh", "Nawabganj", "Ramnagar", "Ramsanehighat", "Sirauli Gauspur"],
    "Bareilly": ["Bareilly", "Aonla", "Baheri", "Faridpur", "Meerganj", "Nawabganj"],
    "Basti": ["Basti", "Bhanpur", "Harraiya", "Kaptanganj", "Rudhauli"],
    "Bhadohi": ["Bhadohi", "Aurai", "Gyanpur"],
    "Bijnor": ["Bijnor", "Chandpur", "Dhampur", "Nagina", "Najibabad", "Noorpur", "Seohara"],
    "Budaun": ["Budaun", "Bilsi", "Bisauli", "Dataganj", "Gunnaur", "Sahaswan", "Ujhani"],
    "Bulandshahr": ["Bulandshahr", "Anupshahr", "Debai", "Khurja", "Shikarpur", "Siana", "Sikandrabad"],
    "Chandauli": ["Chandauli", "Chakiya", "Mughal Sarai", "Naugarh", "Sakaldiha", "Sakteshgarh"],
    "Chitrakoot": ["Chitrakoot", "Karwi", "Manikpur", "Mau"],
    "Deoria": ["Deoria", "Barhaj", "Bhatpar Rani", "Lar", "Pathardeva", "Rampur Karkhana", "Rudrapur", "Salempur"],
    "Etah": ["Etah", "Aliganj", "Awagarh", "Jalesar", "Kasganj", "Marhara", "Patiyali"],
    "Etawah": ["Etawah", "Bharthana", "Jaswantnagar", "Saifai"],
    "Farrukhabad": ["Farrukhabad", "Amritpur", "Kaimganj", "Kamalganj", "Kayamganj", "Shamsabad"],
    "Fatehpur": ["Fatehpur", "Bindki", "Dhata", "Husainganj", "Khaga", "Malwan", "Teliyani"],
    "Firozabad": ["Firozabad", "Jasrana", "Shikohabad", "Sirsaganj", "Tundla"],
    "Gautam Buddha Nagar": ["Noida", "Dadri", "Jewar"],
    "Ghaziabad": ["Ghaziabad", "Hapur", "Loni", "Modinagar", "Muradnagar"],
    "Ghazipur": ["Ghazipur", "Jangipur", "Karanda", "Mohammadabad", "Saidpur", "Zamania"],
    "Gonda": ["Gonda", "Colonelganj", "Katra Bazar", "Mankapur", "Nawabganj", "Tarabganj"],
    "Gorakhpur": ["Gorakhpur", "Bansgaon", "Bhathat", "Campierganj", "Chauri Chaura", "Gola", "Khajni", "Sahjanwa"],
    "Hamirpur": ["Hamirpur", "Maudaha", "Muskara", "Rath", "Sumerpur"],
    "Hapur": ["Hapur", "Dhaulana", "Garh Mukteshwar", "Garhmukteshwar"],
    "Hardoi": ["Hardoi", "Bilgram", "Madhoganj", "Pihani", "Sandila", "Shahabad", "Sawan"],
    "Hathras": ["Hathras", "Mursan", "Sadabad", "Sasni"],
    "Jalaun": ["Orai", "Jalaun", "Kalpi", "Konch", "Madhaugarh"],
    "Jaunpur": ["Jaunpur", "Badlapur", "Kerakat", "Machhali Shahar", "Mungra Badshahpur", "Shahganj"],
    "Jhansi": ["Jhansi", "Babina", "Bangra", "Chirgaon", "Garautha", "Mauranipur", "Moth"],
    "Kannauj": ["Kannauj", "Chhibramau", "Gursahaiganj", "Talgram", "Tirwa"],
    "Kanpur Dehat": ["Akbarpur", "Derapur", "Ghatampur", "Rasulabad", "Sikandra"],
    "Kanpur Nagar": ["Kanpur", "Bilhaur", "Chaubepur", "Kalyanpur", "Shivrajpur"],
    "Kasganj": ["Kasganj", "Amanpur", "Ganj Dundwara", "Patiyali", "Sahawar", "Soron"],
    "Kaushambi": ["Kaushambi", "Chail", "Manjhanpur", "Sarai Akil", "Sirathu"],
    "Kushinagar": ["Kushinagar", "Hata", "Khadda", "Padrauna", "Ramkola", "Sewarhi", "Tamkuhi Raj"],
    "Lakhimpur Kheri": ["Lakhimpur", "Dhaurhara", "Gola Gokarnath", "Kasta", "Mitauli", "Mohammadi", "Nighasan", "Palia Kalan", "Phoolbehar"],
    "Lalitpur": ["Lalitpur", "Jakhaura", "Mandawara", "Mehroni", "Talbehat"],
    "Lucknow": ["Lucknow", "Bakshi Ka Talab", "Chinhat", "Malihabad", "Mohanlalganj", "Sarojini Nagar"],
    "Maharajganj": ["Maharajganj", "Anand Nagar", "Farenda", "Ghughli", "Nautanwa", "Nichlaul", "Partawal", "Siswa Bazar"],
    "Mahoba": ["Mahoba", "Charkhari", "Kabrai", "Kulpahar"],
    "Mainpuri": ["Mainpuri", "Bhogaon", "Ghiror", "Karhal", "Kishni", "Kuraoli", "Shikohabad"],
    "Mathura": ["Mathura", "Baldeo", "Chhata", "Farah", "Govardhan", "Mant", "Mat", "Nandgaon", "Vrindavan"],
    "Mau": ["Mau", "Ghosi", "Kopaganj", "Madhuban", "Muhammadabad"],
    "Meerut": ["Meerut", "Hapur", "Kithore", "Mawana", "Sardhana"],
    "Mirzapur": ["Mirzapur", "Chunar", "Hallia", "Lalganj", "Majhawan", "Marihan", "Nagar", "Rajgarh"],
    "Moradabad": ["Moradabad", "Bilari", "Chandausi", "Kundarki", "Thakurdwara"],
    "Muzaffarnagar": ["Muzaffarnagar", "Budhana", "Charthawal", "Jansath", "Kairana", "Khatauli", "Purqazi", "Shahpur"],
    "Pilibhit": ["Pilibhit", "Amariya", "Barkhera", "Bisalpur", "Puranpur"],
    "Pratapgarh": ["Pratapgarh", "Kunda", "Lalganj", "Mandhata", "Patti", "Rampur Kunda", "Sandwa"],
    "Prayagraj": ["Prayagraj", "Bara", "Chaka", "Handia", "Karchhana", "Kaurihar", "Meja", "Phulpur", "Soraon"],
    "Rae Bareli": ["Rae Bareli", "Dalmau", "Lalganj", "Maharajganj", "Salon", "Unchahar"],
    "Rampur": ["Rampur", "Bilaspur", "Milak", "Shahabad", "Suar", "Tanda"],
    "Saharanpur": ["Saharanpur", "Behat", "Deoband", "Gangoh", "Nakur", "Nanauta", "Rampur Maniharan", "Roorkee", "Sarsawa"],
    "Sambhal": ["Sambhal", "Asmoli", "Bahjoi", "Chandausi", "Gunnaur", "Rajpura"],
    "Sant Kabir Nagar": ["Khalilabad", "Baghauli", "Hainsar Bazar", "Mehdawal", "Santha"],
    "Shahjahanpur": ["Shahjahanpur", "Jalalabad", "Khutar", "Mirzapur", "Powayan", "Tilhar"],
    "Shamli": ["Shamli", "Kairana", "Thana Bhawan", "Un"],
    "Shravasti": ["Bhinga", "Gilaula", "Huzurpur", "Ikauna", "Jamunaha", "Sirsia"],
    "Siddharthnagar": ["Siddharthnagar", "Bhanwapur", "Domariyaganj", "Itwa", "Naugarh", "Shohratgarh", "Uska Bazar"],
    "Sitapur": ["Sitapur", "Biswan", "Hargaon", "Laharpur", "Mahmudabad", "Misrikh", "Reusa", "Sidhauli"],
    "Sonbhadra": ["Robertsganj", "Babhani", "Chopan", "Dudhi", "Ghorawal", "Myorpur", "Obra"],
    "Sultanpur": ["Sultanpur", "Amethi", "Baldirai", "Dostpur", "Dubeypur", "Kadipur", "Lambhua"],
    "Unnao": ["Unnao", "Asoha", "Bangarmau", "Bighapur", "Hasanganj", "Nawabganj", "Purwa", "Safipur"],
    "Varanasi": ["Varanasi", "Arajiline", "Chiraigaon", "Harhua", "Kashi Vidyapeeth", "Pindra", "Rajatalab", "Sewapuri"]
  },

  "Uttarakhand": {
    "Almora": ["Almora", "Bhainsiyachhana", "Bhikiyasain", "Chaukhutia", "Dwarahat", "Jainti", "Lamgara", "Ranikhet", "Salt", "Sult", "Syaldeh", "Tarikhet"],
    "Bageshwar": ["Bageshwar", "Baijnath", "Garur", "Kapkot"],
    "Chamoli": ["Gopeshwar", "Dasholi", "Gairsain", "Joshimath", "Karnaprayag", "Narayanbagar", "Pokhari", "Tharali"],
    "Champawat": ["Champawat", "Barakot", "Lohaghat", "Pati"],
    "Dehradun": ["Dehradun", "Chakrata", "Doiwala", "Kalsi", "Rishikesh", "Sahaspur", "Tyuni", "Vikasnagar"],
    "Haridwar": ["Haridwar", "Bahadrabad", "Bhagwanpur", "Khanpur", "Laksar", "Narsan", "Roorkee"],
    "Nainital": ["Nainital", "Betalghat", "Bhimtal", "Dhari", "Haldwani", "Kotabagh", "Okhalkanda", "Ramnagar", "Ramgarh"],
    "Pauri Garhwal": ["Pauri", "Bironkhal", "Dwarikhal", "Ekeshwar", "Idwal", "Kaljikhal", "Khirsu", "Kot", "Lansdowne", "Nainidanda", "Pabau", "Pabo", "Pokhra", "Rikhnikhal", "Satpuli", "Thalisain", "Yamkeshwar"],
    "Pithoragarh": ["Pithoragarh", "Berinag", "Didihat", "Dharchula", "Gangolihat", "Kanalichhina", "Munsiari"],
    "Rudraprayag": ["Rudraprayag", "Augustmuni", "Jakholi", "Kedarnath", "Ukhimath"],
    "Tehri Garhwal": ["Tehri", "Chamba", "Devprayag", "Dhanolti", "Ghansali", "Jakhnidhar", "Jaunpur", "Kirtinagar", "Narendra Nagar", "New Tehri", "Pratapnagar"],
    "Udham Singh Nagar": ["Rudrapur", "Bazpur", "Gadarpur", "Jaspur", "Kashipur", "Khatima", "Kichha", "Sitarganj"],
    "Uttarkashi": ["Uttarkashi", "Bhatwari", "Chinyalisaur", "Dunda", "Mori", "Naugaon", "Purola"]
  },

  "West Bengal": {
    "Alipurduar": ["Alipurduar", "Falakata", "Kalchini", "Kumargram", "Madarihat"],
    "Bankura": ["Bankura", "Barjora", "Bishnupur", "Chhatna", "Gangajalghati", "Hirbandh", "Indpur", "Indus", "Khatra", "Kotulpur", "Mejia", "Onda", "Patrasayer", "Raipur", "Ranibandh", "Saltora", "Simlapal", "Sonamukhi", "Taldangra"],
    "Birbhum": ["Suri", "Bolpur", "Dubrajpur", "Khoyrasol", "Labpur", "Labhpur", "Mohammad Bazar", "Murarai", "Nalhati", "Rajnagar", "Rampurhat", "Sainthia"],
    "Cooch Behar": ["Cooch Behar", "Dinhata", "Mathabhanga", "Mekhliganj", "Sitai", "Sitalkuchi", "Tufanganj"],
    "Dakshin Dinajpur": ["Balurghat", "Bansihari", "Buniadpur", "Cumari", "Gangarampur", "Harirampur", "Kushmandi", "Tapan"],
    "Darjeeling": ["Darjeeling", "Jorebunglow", "Kalimpong", "Kurseong", "Mirik", "Phansidewa", "Rangli Rangliot", "Siliguri"],
    "Hooghly": ["Chinsurah", "Arambag", "Balagarh", "Chanditala", "Dhaniakhali", "Goghat", "Haripal", "Jangipara", "Khanakul", "Pandua", "Polba", "Pursurah", "Serampore", "Singur", "Tarakeswar", "Uttarpara"],
    "Howrah": ["Howrah", "Amta", "Bagnan", "Bally", "Domjur", "Jagatballavpur", "Panchla", "Sankrail", "Shyampur", "Udaynarayanpur", "Uluberia"],
    "Jalpaiguri": ["Jalpaiguri", "Dhupguri", "Kalchini", "Mal", "Maynaguri", "Nagrakata", "Rajganj"],
    "Jhargram": ["Jhargram", "Binpur", "Gopiballavpur", "Jamboni", "Nayagram", "Sankrail", "Silda"],
    "Kalimpong": ["Kalimpong", "Gorubathan", "Kalijhora"],
    "Kolkata": ["Kolkata", "Alipore", "Behala", "Dum Dum", "Entally", "Jadavpur", "Jorasanko", "Kasba", "Maniktala", "Shyampukur"],
    "Malda": ["Malda", "Bamangola", "Chanchal", "English Bazar", "Gazole", "Habibpur", "Harischandrapur", "Kaliachak", "Manikchak", "Old Malda", "Ratua"],
    "Murshidabad": ["Berhampore", "Baharampur", "Beldanga", "Bharatpur", "Domkal", "Farakka", "Hariharpara", "Jalangi", "Kandi", "Khargram", "Lalgola", "Murshidabad", "Nabagram", "Nowda", "Raghunathganj", "Raninagar", "Samserganj", "Suti"],
    "Nadia": ["Krishnanagar", "Chakdaha", "Chapra", "Hanskhali", "Haringhata", "Karimpur", "Kalyani", "Nabadwip", "Nakashipara", "Ranaghat", "Santipur", "Tehatta"],
    "North 24 Parganas": ["Barasat", "Amdanga", "Baduria", "Bagdah", "Bangaon", "Basirhat", "Bongaon", "Deganga", "Gaighata", "Habra", "Haroa", "Hasnabad", "Hingalganj", "Minakhan", "Rajarhat", "Sandeshkhali", "Swarupnagar"],
    "Paschim Bardhaman": ["Asansol", "Andal", "Barabani", "Durgapur", "Faridpur", "Jamuria", "Kanksa", "Kulti", "Ondal", "Pandabeswar", "Raniganj", "Salanpur"],
    "Paschim Medinipur": ["Medinipur", "Chandrakona", "Daspur", "Debra", "Garbeta", "Ghatal", "Keshpur", "Kharagpur", "Narayangarh", "Pingla", "Sabang", "Salboni", "Sankrail", "Shilda"],
    "Purba Bardhaman": ["Bardhaman", "Ausgram", "Bhatar", "Budbud", "Galsi", "Jamalpur", "Kalna", "Katwa", "Ketugram", "Khandaghosh", "Mangalkot", "Memari", "Monteswar", "Purbasthali", "Raina"],
    "Purba Medinipur": ["Tamluk", "Bhagabanpur", "Chandipur", "Contai", "Deshopran", "Egra", "Haldia", "Khejuri", "Mahishadal", "Moyna", "Nandakumar", "Nandigram", "Panskura", "Patashpur", "Ramnagar"],
    "Purulia": ["Purulia", "Arsha", "Bagmundi", "Barabazar", "Balarampur", "Bandwan", "Hura", "Jhalda", "Joypur", "Kashipur", "Manbazar", "Neturia", "Para", "Puncha", "Raghunathpur", "Santuri"],
    "South 24 Parganas": ["Alipore", "Baruipur", "Bishnupur", "Budge Budge", "Canning", "Diamond Harbour", "Falta", "Gosaba", "Jaynagar", "Kakdwip", "Kulpi", "Kultali", "Magrahat", "Mandirbazar", "Mathurapur", "Namkhana", "Patharpratima", "Sagar"],
    "Uttar Dinajpur": ["Raiganj", "Chopra", "Goalpokhar", "Hemtabad", "Islampur", "Itahar", "Karandighi"]
  }
};



// MapMyIndia Configuration
export const mapMyIndiaConfig = {
  apiKey: import.meta.env.REACT_APP_MAPMYINDIA_API_KEY, // Your API Key
  baseUrl: 'https://apis.mapmyindia.com/advancedmaps/v1',
  geocodeUrl: 'https://atlas.mapmyindia.com/api/places/geocode',
  directionsUrl: 'https://apis.mapmyindia.com/advancedmaps/v1/route'
};

